// DO NOT EDIT — generated from registry/*.yaml by `npm run generate-static`
import type { AvatarModelPricing } from './types';

export const STATIC_AVATAR_PRICING: AvatarModelPricing[] = [
  {
    modelId: 'fal-heygen-avatar4-i2v',
    provider: 'fal',
    displayName: 'HeyGen Photo Avatar 4 (FAL Image-to-Video)',
    costPerMinute: 6,
    avatarType: 'standard',
    resolution: null,
    maxDuration: null,
    qualityMode: null,
    lipSync: true,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-05-01',
  },
  {
    modelId: 'fal-heygen-avatar4-twin',
    provider: 'fal',
    displayName: 'FAL HeyGen Avatar 4 Digital Twin',
    costPerMinute: 6,
    avatarType: 'premium',
    resolution: null,
    maxDuration: null,
    qualityMode: null,
    lipSync: true,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-05-01',
  },
  {
    modelId: 'fal-kling-lipsync-t2v',
    provider: 'fal',
    displayName: 'Kling Video LipSync Text-to-Video (FAL)',
    costPerMinute: 0.84,
    avatarType: 'standard',
    resolution: null,
    maxDuration: null,
    qualityMode: null,
    lipSync: true,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2026-03-13',
  },
  {
    modelId: 'fal-ltx2.3-a2v-1080p',
    provider: 'fal',
    displayName: 'FAL LTX-2.3 Audio-to-Video 1080p',
    costPerMinute: 6,
    avatarType: 'standard',
    resolution: '1080p',
    maxDuration: 20,
    qualityMode: 'standard',
    lipSync: true,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2026-03-16',
  },
  {
    modelId: 'fal-veed-fabric-1-480p',
    provider: 'fal',
    displayName: 'VEED Fabric 1.0 480p (FAL)',
    costPerMinute: 4.8,
    avatarType: 'standard',
    resolution: '480p',
    maxDuration: null,
    qualityMode: null,
    lipSync: true,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2026-03-13',
  },
  {
    modelId: 'fal-veed-fabric-1-720p',
    provider: 'fal',
    displayName: 'VEED Fabric 1.0 720p (FAL)',
    costPerMinute: 9,
    avatarType: 'standard',
    resolution: '720p',
    maxDuration: null,
    qualityMode: null,
    lipSync: true,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2026-03-13',
  },
  {
    modelId: 'heygen-avatar-iv',
    provider: 'heygen',
    displayName: 'HeyGen Interactive Avatar IV',
    costPerMinute: 6,
    avatarType: 'premium',
    resolution: '1080p',
    maxDuration: 180,
    qualityMode: 'premium',
    lipSync: true,
    source: 'seed',
    status: 'deprecated',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-03-01',
  },
  {
    modelId: 'heygen-avatar-standard',
    provider: 'heygen',
    displayName: 'HeyGen Standard Avatar',
    costPerMinute: 1.002,
    avatarType: 'standard',
    resolution: '1080p',
    maxDuration: 600,
    qualityMode: 'standard',
    lipSync: true,
    source: 'seed',
    status: 'deprecated',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-01-15',
  },
  {
    modelId: 'heygen-digital-twin-iii',
    provider: 'heygen',
    displayName: 'HeyGen Digital Twin III',
    costPerMinute: 1.998,
    avatarType: 'standard',
    resolution: '1080p',
    maxDuration: 600,
    qualityMode: 'standard',
    lipSync: true,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-09-12',
  },
  {
    modelId: 'heygen-digital-twin-iv',
    provider: 'heygen',
    displayName: 'HeyGen Digital Twin IV',
    costPerMinute: 6,
    avatarType: 'premium',
    resolution: '1080p',
    maxDuration: 600,
    qualityMode: 'premium',
    lipSync: true,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-05-01',
  },
  {
    modelId: 'heygen-photo-avatar-iii',
    provider: 'heygen',
    displayName: 'HeyGen Photo Avatar III',
    costPerMinute: 1.002,
    avatarType: 'standard',
    resolution: '1080p',
    maxDuration: 600,
    qualityMode: 'standard',
    lipSync: true,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-09-12',
  },
  {
    modelId: 'heygen-photo-avatar-iv',
    provider: 'heygen',
    displayName: 'HeyGen Photo Avatar IV',
    costPerMinute: 6,
    avatarType: 'premium',
    resolution: '1080p',
    maxDuration: 180,
    qualityMode: 'premium',
    lipSync: true,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-05-01',
  },
  {
    modelId: 'heygen-public-avatar-iii',
    provider: 'heygen',
    displayName: 'HeyGen Public Avatar III',
    costPerMinute: 1.002,
    avatarType: 'standard',
    resolution: '1080p',
    maxDuration: 600,
    qualityMode: 'standard',
    lipSync: true,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-09-12',
  },
  {
    modelId: 'heygen-public-avatar-iv',
    provider: 'heygen',
    displayName: 'HeyGen Public Avatar IV',
    costPerMinute: 6,
    avatarType: 'premium',
    resolution: '1080p',
    maxDuration: 180,
    qualityMode: 'premium',
    lipSync: true,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-05-01',
  },
  {
    modelId: 'heygen-translation-precision',
    provider: 'heygen',
    displayName: 'HeyGen Video Translation (Precision)',
    costPerMinute: 6,
    avatarType: 'translation',
    resolution: '1080p',
    maxDuration: 1800,
    qualityMode: 'standard',
    lipSync: true,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-11-17',
  },
  {
    modelId: 'heygen-translation-proofread',
    provider: 'heygen',
    displayName: 'HeyGen Video Translation (Proofread)',
    costPerMinute: 0.498,
    avatarType: 'translation',
    resolution: '1080p',
    maxDuration: 1800,
    qualityMode: 'standard',
    lipSync: false,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-08-01',
  },
  {
    modelId: 'heygen-translation-speed',
    provider: 'heygen',
    displayName: 'HeyGen Video Translation (Speed)',
    costPerMinute: 3,
    avatarType: 'translation',
    resolution: '1080p',
    maxDuration: 1800,
    qualityMode: 'standard',
    lipSync: false,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-11-17',
  },
  {
    modelId: 'replicate-dreamactor-m2',
    provider: 'replicate',
    displayName: 'Replicate DreamActor M2.0',
    costPerMinute: 3,
    avatarType: 'standard',
    resolution: null,
    maxDuration: null,
    qualityMode: null,
    lipSync: true,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2026-01-01',
  },
  {
    modelId: 'replicate-sadtalker',
    provider: 'replicate',
    displayName: 'Replicate SadTalker',
    costPerMinute: 1,
    avatarType: 'standard',
    resolution: null,
    maxDuration: null,
    qualityMode: null,
    lipSync: true,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2023-06-01',
  },
  {
    modelId: 'replicate-veed-fabric-480p',
    provider: 'replicate',
    displayName: 'Replicate VEED Fabric 1.0 480p',
    costPerMinute: 4.8,
    avatarType: 'standard',
    resolution: '480p',
    maxDuration: 300,
    qualityMode: null,
    lipSync: true,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2026-01-01',
  },
  {
    modelId: 'replicate-veed-fabric-720p',
    provider: 'replicate',
    displayName: 'Replicate VEED Fabric 1.0 720p',
    costPerMinute: 9,
    avatarType: 'standard',
    resolution: '720p',
    maxDuration: 300,
    qualityMode: null,
    lipSync: true,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2026-01-01',
  },
  {
    modelId: 'replicate-video-retalking',
    provider: 'replicate',
    displayName: 'Replicate VideoRetalking',
    costPerMinute: 1.5,
    avatarType: 'standard',
    resolution: null,
    maxDuration: null,
    qualityMode: null,
    lipSync: true,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2023-01-01',
  },
  {
    modelId: 'replicate-wav2lip',
    provider: 'replicate',
    displayName: 'Replicate Wav2Lip',
    costPerMinute: 0.5,
    avatarType: 'standard',
    resolution: null,
    maxDuration: null,
    qualityMode: null,
    lipSync: true,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2022-06-01',
  },
  {
    modelId: 'runway-characters',
    provider: 'runway',
    displayName: 'Runway Characters (GWM-1 Avatars)',
    costPerMinute: 0.2,
    avatarType: 'standard',
    resolution: '720p',
    maxDuration: null,
    qualityMode: null,
    lipSync: true,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2026-03-09',
  },
];
