import type { AvatarModelPricing } from './types';

export const STATIC_AVATAR_PRICING: AvatarModelPricing[] = [
  // HeyGen — Standard Avatar
  // 1 credit = 1 min of video, $0.99/credit on API plan
  {
    modelId: 'heygen-avatar-standard',
    provider: 'heygen',
    displayName: 'HeyGen Standard Avatar',
    costPerMinute: 0.99,
    avatarType: 'standard',
    resolution: '1080p',
    maxDuration: 600,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-01-15',
  },
  // HeyGen — Interactive Avatar (Avatar IV)
  // 6 credits/min = $5.94/min
  {
    modelId: 'heygen-avatar-iv',
    provider: 'heygen',
    displayName: 'HeyGen Interactive Avatar IV',
    costPerMinute: 5.94,
    avatarType: 'premium',
    resolution: '1080p',
    maxDuration: 180,
    qualityMode: 'premium',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-03-01',
  },
  // HeyGen — Video Translation
  // 3 credits/min = $2.97/min
  {
    modelId: 'heygen-video-translation',
    provider: 'heygen',
    displayName: 'HeyGen Video Translation',
    costPerMinute: 2.97,
    avatarType: 'translation',
    resolution: '1080p',
    maxDuration: 1800,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-06-01',
  },
  // HeyGen Avatar III variants — launched 2024-09-12
  {
    modelId: 'heygen-digital-twin-iii',
    provider: 'heygen',
    displayName: 'HeyGen Digital Twin III',
    costPerMinute: 0.99,
    avatarType: 'standard',
    resolution: '1080p',
    maxDuration: 600,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-09-12',
  },
  {
    modelId: 'heygen-photo-avatar-iii',
    provider: 'heygen',
    displayName: 'HeyGen Photo Avatar III',
    costPerMinute: 0.99,
    avatarType: 'standard',
    resolution: '1080p',
    maxDuration: 600,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-09-12',
  },
  {
    modelId: 'heygen-public-avatar-iii',
    provider: 'heygen',
    displayName: 'HeyGen Public Avatar III',
    costPerMinute: 0.99,
    avatarType: 'standard',
    resolution: '1080p',
    maxDuration: 600,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-09-12',
  },
  // HeyGen Avatar IV variants — launched 2025-05-01
  {
    modelId: 'heygen-digital-twin-iv',
    provider: 'heygen',
    displayName: 'HeyGen Digital Twin IV',
    costPerMinute: 5.94,
    avatarType: 'premium',
    resolution: '1080p',
    maxDuration: 180,
    qualityMode: 'premium',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-05-01',
  },
  {
    modelId: 'heygen-photo-avatar-iv',
    provider: 'heygen',
    displayName: 'HeyGen Photo Avatar IV',
    costPerMinute: 5.94,
    avatarType: 'premium',
    resolution: '1080p',
    maxDuration: 180,
    qualityMode: 'premium',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-05-01',
  },
  {
    modelId: 'heygen-public-avatar-iv',
    provider: 'heygen',
    displayName: 'HeyGen Public Avatar IV',
    costPerMinute: 5.94,
    avatarType: 'premium',
    resolution: '1080p',
    maxDuration: 180,
    qualityMode: 'premium',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-05-01',
  },
  // HeyGen Video Translation variants
  {
    modelId: 'heygen-translate-precision',
    provider: 'heygen',
    displayName: 'HeyGen Video Translation Precision Mode',
    costPerMinute: 2.97,
    avatarType: 'translation',
    resolution: '1080p',
    maxDuration: 1800,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-11-17',
  },
  {
    modelId: 'heygen-translate-speed',
    provider: 'heygen',
    displayName: 'HeyGen Video Translation Speed Mode',
    costPerMinute: 2.97,
    avatarType: 'translation',
    resolution: '1080p',
    maxDuration: 1800,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-11-17',
  },
  {
    modelId: 'heygen-translate-proofread',
    provider: 'heygen',
    displayName: 'HeyGen Video Translation Proofread',
    costPerMinute: 2.97,
    avatarType: 'translation',
    resolution: '1080p',
    maxDuration: 1800,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-08-01',
  },
  {
    modelId: 'heygen-translation-precision',
    provider: 'heygen',
    displayName: 'HeyGen Video Translation — Precision Mode',
    costPerMinute: 2.97,
    avatarType: 'translation',
    resolution: '1080p',
    maxDuration: 1800,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-11-17',
  },
  {
    modelId: 'heygen-translation-speed',
    provider: 'heygen',
    displayName: 'HeyGen Video Translation — Speed Mode',
    costPerMinute: 2.97,
    avatarType: 'translation',
    resolution: '1080p',
    maxDuration: 1800,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-11-17',
  },
  {
    modelId: 'heygen-translation-proofread',
    provider: 'heygen',
    displayName: 'HeyGen Video Translation — Proofread',
    costPerMinute: 2.97,
    avatarType: 'translation',
    resolution: '1080p',
    maxDuration: 1800,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-08-01',
  },
];
