// DO NOT EDIT — generated from registry/*.yaml by `npm run generate-static`
import type { MusicModelPricing } from './types';

export const STATIC_MUSIC_PRICING: MusicModelPricing[] = [
  {
    modelId: 'elevenlabs-eleven-music',
    provider: 'elevenlabs',
    displayName: 'ElevenLabs Eleven Music',
    costPerMinute: 0.5,
    maxDuration: null,
    outputFormat: 'mp3',
    vocals: true,
    official: true,
    pricingNote: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-06-01',
  },
  {
    modelId: 'soundverse-music',
    provider: 'soundverse',
    displayName: 'Soundverse Music Generation',
    costPerMinute: 0.0125,
    maxDuration: 240,
    outputFormat: 'mp3',
    vocals: true,
    official: true,
    pricingNote: 'Approximated from ~$0.05/song at ~4 min avg',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-01-01',
  },
  {
    modelId: 'sunoapi-suno-v4.5',
    provider: 'sunoapi',
    displayName: 'Suno v4.5 via SunoAPI.org',
    costPerMinute: 0.00625,
    maxDuration: 480,
    outputFormat: 'mp3',
    vocals: true,
    official: false,
    pricingNote: 'Unofficial wrapper. ~$0.025/song ($0.005/credit x 5 credits) at ~4 min avg',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-09-01',
  },
];
