import type { ImageModelPricing } from './types';

export const STATIC_IMAGE_PRICING: ImageModelPricing[] = [
  // OpenAI
  {
    modelId: 'dall-e-3-standard-1024',
    provider: 'openai',
    displayName: 'DALL-E 3 Standard 1024',
    pricePerImage: 0.040,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    lastUpdated: null,
    launchDate: '2023-10-01',
  },
  {
    modelId: 'dall-e-3-hd-1024',
    provider: 'openai',
    displayName: 'DALL-E 3 HD 1024',
    pricePerImage: 0.080,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'hd',
    maxResolution: null,
    supportedFormats: ['png'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    lastUpdated: null,
    launchDate: '2023-10-01',
  },
  {
    modelId: 'dall-e-3-standard-1792',
    provider: 'openai',
    displayName: 'DALL-E 3 Standard 1792',
    pricePerImage: 0.080,
    pricePerMegapixel: null,
    defaultResolution: '1024x1792',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    lastUpdated: null,
    launchDate: '2023-10-01',
  },
  {
    modelId: 'dall-e-3-hd-1792',
    provider: 'openai',
    displayName: 'DALL-E 3 HD 1792',
    pricePerImage: 0.120,
    pricePerMegapixel: null,
    defaultResolution: '1024x1792',
    qualityTier: 'hd',
    maxResolution: null,
    supportedFormats: ['png'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    lastUpdated: null,
    launchDate: '2023-10-01',
  },
  {
    modelId: 'dall-e-2-1024',
    provider: 'openai',
    displayName: 'DALL-E 2 1024',
    pricePerImage: 0.020,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    lastUpdated: null,
    launchDate: '2022-11-01',
  },
  {
    modelId: 'gpt-image-1-low',
    provider: 'openai',
    displayName: 'GPT Image 1 Low',
    pricePerImage: 0.011,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png', 'webp'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    lastUpdated: null,
    launchDate: '2025-04-23',
  },
  {
    modelId: 'gpt-image-1-medium',
    provider: 'openai',
    displayName: 'GPT Image 1 Medium',
    pricePerImage: 0.042,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png', 'webp'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    lastUpdated: null,
    launchDate: '2025-04-23',
  },
  {
    modelId: 'gpt-image-1-high',
    provider: 'openai',
    displayName: 'GPT Image 1 High',
    pricePerImage: 0.167,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'hd',
    maxResolution: null,
    supportedFormats: ['png', 'webp'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    lastUpdated: null,
    launchDate: '2025-04-23',
  },

  // Google
  {
    modelId: 'imagen-3',
    provider: 'google',
    displayName: 'Imagen 3',
    pricePerImage: 0.04,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    lastUpdated: null,
    launchDate: '2024-08-01',
  },
  {
    modelId: 'imagen-4-fast',
    provider: 'google',
    displayName: 'Imagen 4 Fast',
    pricePerImage: 0.02,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    lastUpdated: null,
    launchDate: '2025-05-01',
  },
  {
    modelId: 'imagen-4-standard',
    provider: 'google',
    displayName: 'Imagen 4 Standard',
    pricePerImage: 0.04,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    lastUpdated: null,
    launchDate: '2025-05-01',
  },
  {
    modelId: 'imagen-4-ultra',
    provider: 'google',
    displayName: 'Imagen 4 Ultra',
    pricePerImage: 0.06,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'hd',
    maxResolution: null,
    supportedFormats: ['png'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    lastUpdated: null,
    launchDate: '2025-05-01',
  },

  // Stability AI
  {
    modelId: 'sd-3.5-large',
    provider: 'stability',
    displayName: 'SD 3.5 Large',
    pricePerImage: 0.065,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png', 'webp'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    lastUpdated: null,
    launchDate: '2024-10-22',
  },
  {
    modelId: 'sd-3.5-large-turbo',
    provider: 'stability',
    displayName: 'SD 3.5 Large Turbo',
    pricePerImage: 0.04,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png', 'webp'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    lastUpdated: null,
    launchDate: '2024-10-22',
  },
  {
    modelId: 'stable-image-ultra',
    provider: 'stability',
    displayName: 'Stable Image Ultra',
    pricePerImage: 0.08,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'ultra',
    maxResolution: null,
    supportedFormats: ['png', 'webp'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    lastUpdated: null,
    launchDate: '2024-04-01',
  },
  {
    modelId: 'stable-image-core',
    provider: 'stability',
    displayName: 'Stable Image Core',
    pricePerImage: 0.03,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png', 'webp'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    lastUpdated: null,
    launchDate: '2024-04-01',
  },

  // Black Forest Labs
  {
    modelId: 'flux-1.1-pro',
    provider: 'bfl',
    displayName: 'FLUX 1.1 Pro',
    pricePerImage: 0.04,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png', 'jpeg'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    lastUpdated: null,
    launchDate: '2024-10-01',
  },
  {
    modelId: 'flux-1.1-pro-ultra',
    provider: 'bfl',
    displayName: 'FLUX 1.1 Pro Ultra',
    pricePerImage: 0.06,
    pricePerMegapixel: null,
    defaultResolution: '2048x2048',
    qualityTier: 'hd',
    maxResolution: '2048x2048',
    supportedFormats: ['png', 'jpeg'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    lastUpdated: null,
    launchDate: '2024-11-01',
  },
  {
    modelId: 'flux-2-klein',
    provider: 'bfl',
    displayName: 'FLUX 2 Klein',
    pricePerImage: 0.014,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png', 'jpeg'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    lastUpdated: null,
    launchDate: '2025-01-15',
  },
  {
    modelId: 'flux-2-pro',
    provider: 'bfl',
    displayName: 'FLUX 2 Pro',
    pricePerImage: 0.05,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png', 'jpeg'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    lastUpdated: null,
    launchDate: '2025-01-15',
  },
  {
    modelId: 'flux-2-max',
    provider: 'bfl',
    displayName: 'FLUX 2 Max',
    pricePerImage: 0.06,
    pricePerMegapixel: null,
    defaultResolution: '2048x2048',
    qualityTier: 'hd',
    maxResolution: '2048x2048',
    supportedFormats: ['png', 'jpeg'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    lastUpdated: null,
    launchDate: '2025-01-15',
  },
  {
    modelId: 'flux-1-kontext-pro',
    provider: 'bfl',
    displayName: 'FLUX 1 Kontext Pro',
    pricePerImage: 0.04,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png', 'jpeg'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    lastUpdated: null,
    launchDate: '2025-06-01',
  },

  // Amazon
  {
    modelId: 'nova-canvas-standard-1024',
    provider: 'amazon',
    displayName: 'Nova Canvas Standard 1024',
    pricePerImage: 0.04,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    lastUpdated: null,
    launchDate: '2024-12-03',
  },
  {
    modelId: 'nova-canvas-premium-1024',
    provider: 'amazon',
    displayName: 'Nova Canvas Premium 1024',
    pricePerImage: 0.06,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'hd',
    maxResolution: null,
    supportedFormats: ['png'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    lastUpdated: null,
    launchDate: '2024-12-03',
  },
  {
    modelId: 'nova-canvas-standard-2048',
    provider: 'amazon',
    displayName: 'Nova Canvas Standard 2048',
    pricePerImage: 0.06,
    pricePerMegapixel: null,
    defaultResolution: '2048x2048',
    qualityTier: 'standard',
    maxResolution: '2048x2048',
    supportedFormats: ['png'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    lastUpdated: null,
    launchDate: '2024-12-03',
  },
  {
    modelId: 'nova-canvas-premium-2048',
    provider: 'amazon',
    displayName: 'Nova Canvas Premium 2048',
    pricePerImage: 0.08,
    pricePerMegapixel: null,
    defaultResolution: '2048x2048',
    qualityTier: 'hd',
    maxResolution: '2048x2048',
    supportedFormats: ['png'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    lastUpdated: null,
    launchDate: '2024-12-03',
  },

  // Recraft
  {
    modelId: 'recraft-v4-raster',
    provider: 'recraft',
    displayName: 'Recraft V4 Raster',
    pricePerImage: 0.04,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png', 'svg'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    lastUpdated: null,
    launchDate: '2025-01-15',
  },
  {
    modelId: 'recraft-v4-vector',
    provider: 'recraft',
    displayName: 'Recraft V4 Vector',
    pricePerImage: 0.08,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['svg'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    lastUpdated: null,
    launchDate: '2025-01-15',
  },

  // Mistral
  {
    modelId: 'mistral-flux-pro-ultra',
    provider: 'mistral',
    displayName: 'Mistral FLUX Pro Ultra',
    pricePerImage: 0.10,
    pricePerMegapixel: null,
    defaultResolution: '2048x2048',
    qualityTier: 'hd',
    maxResolution: '2048x2048',
    supportedFormats: ['png'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    lastUpdated: null,
    launchDate: '2025-01-15',
  },

  // Bytedance
  {
    modelId: 'seedream-4.5',
    provider: 'bytedance',
    displayName: 'Seedream 4.5',
    pricePerImage: 0.035,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    lastUpdated: null,
    launchDate: '2025-01-15',
  },

  // fal.ai
  {
    modelId: 'fal-recraft-v3',
    provider: 'fal',
    displayName: 'fal Recraft V3',
    pricePerImage: 0.02,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    lastUpdated: null,
    launchDate: '2025-01-15',
  },
  {
    modelId: 'fal-flux-1-pro',
    provider: 'fal',
    displayName: 'fal FLUX 1 Pro',
    pricePerImage: 0.025,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png', 'jpeg'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    lastUpdated: null,
    launchDate: '2025-01-15',
  },
  {
    modelId: 'fal-flux-2-pro',
    provider: 'fal',
    displayName: 'fal FLUX 2 Pro',
    pricePerImage: 0.04,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png', 'jpeg'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    lastUpdated: null,
    launchDate: '2025-01-15',
  },
  {
    modelId: 'fal-ideogram-v2',
    provider: 'fal',
    displayName: 'fal Ideogram V2',
    pricePerImage: 0.08,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    lastUpdated: null,
    launchDate: '2025-01-15',
  },
  {
    modelId: 'fal-sd3',
    provider: 'fal',
    displayName: 'fal SD3',
    pricePerImage: 0.035,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    lastUpdated: null,
    launchDate: '2025-01-15',
  },

  // Ideogram
  {
    modelId: 'ideogram-v3',
    provider: 'ideogram',
    displayName: 'Ideogram V3',
    pricePerImage: 0.05,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    lastUpdated: null,
    launchDate: '2025-01-15',
  },
  {
    modelId: 'ideogram-v3-turbo',
    provider: 'ideogram',
    displayName: 'Ideogram V3 Turbo',
    pricePerImage: 0.03,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    lastUpdated: null,
    launchDate: '2025-01-15',
  },

  // xAI
  {
    modelId: 'aurora-grok-2-image',
    provider: 'xai',
    displayName: 'Aurora Grok 2 Image',
    pricePerImage: 0.07,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    lastUpdated: null,
    launchDate: '2025-01-15',
  },
];
