import type { ModelPricing } from './types';

export const STATIC_PRICING: ModelPricing[] = [
  // Anthropic
  {
    modelId: 'claude-opus-4-6',
    provider: 'anthropic',
    displayName: 'Claude Opus 4.6',
    inputPerMTok: 5,
    outputPerMTok: 25,
    contextWindow: 200000,
    maxOutputTokens: 128000,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2026-02-05',
  },
  {
    modelId: 'claude-sonnet-4-6',
    provider: 'anthropic',
    displayName: 'Claude Sonnet 4.6',
    inputPerMTok: 3,
    outputPerMTok: 15,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2026-02-17',
  },
  {
    modelId: 'claude-haiku-4-5-20251001',
    provider: 'anthropic',
    displayName: 'Claude Haiku 4.5',
    inputPerMTok: 1,
    outputPerMTok: 5,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-10-15',
  },

  // OpenAI
  {
    modelId: 'gpt-5.4',
    provider: 'openai',
    displayName: 'GPT-5.4',
    inputPerMTok: 2.5,
    outputPerMTok: 15,
    contextWindow: 1050000,
    maxOutputTokens: 128000,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2026-03-05',
  },
  {
    modelId: 'gpt-5.4-pro',
    provider: 'openai',
    displayName: 'GPT-5.4 Pro',
    inputPerMTok: 30,
    outputPerMTok: 180,
    contextWindow: 1050000,
    maxOutputTokens: 128000,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2026-03-05',
  },
  {
    modelId: 'gpt-5.3-chat-latest',
    provider: 'openai',
    displayName: 'GPT-5.3 Instant',
    inputPerMTok: 1.75,
    outputPerMTok: 14,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2026-03-03',
  },
  {
    modelId: 'gpt-5.3-codex',
    provider: 'openai',
    displayName: 'GPT-5.3 Codex',
    inputPerMTok: 1.75,
    outputPerMTok: 14,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2026-02-24',
  },
  {
    modelId: 'gpt-5.2',
    provider: 'openai',
    displayName: 'GPT-5.2',
    inputPerMTok: 1.75,
    outputPerMTok: 14,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-12-11',
  },
  {
    modelId: 'gpt-5',
    provider: 'openai',
    displayName: 'GPT-5',
    inputPerMTok: 1.25,
    outputPerMTok: 10,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-08-07',
  },
  {
    modelId: 'gpt-5-mini',
    provider: 'openai',
    displayName: 'GPT-5 Mini',
    inputPerMTok: 0.25,
    outputPerMTok: 2,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-08-07',
  },
  {
    modelId: 'gpt-5-nano',
    provider: 'openai',
    displayName: 'GPT-5 Nano',
    inputPerMTok: 0.05,
    outputPerMTok: 0.40,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-08-07',
  },
  {
    modelId: 'gpt-4.1',
    provider: 'openai',
    displayName: 'GPT-4.1',
    inputPerMTok: 2.0,
    outputPerMTok: 8.0,
    contextWindow: 1000000,
    maxOutputTokens: 32768,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-04-14',
  },
  {
    modelId: 'gpt-4.1-mini',
    provider: 'openai',
    displayName: 'GPT-4.1 Mini',
    inputPerMTok: 0.40,
    outputPerMTok: 1.60,
    contextWindow: 1000000,
    maxOutputTokens: 32768,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-04-14',
  },
  {
    modelId: 'gpt-4.1-nano',
    provider: 'openai',
    displayName: 'GPT-4.1 Nano',
    inputPerMTok: 0.10,
    outputPerMTok: 0.40,
    contextWindow: 1000000,
    maxOutputTokens: 32768,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-04-14',
  },
  {
    modelId: 'gpt-4o',
    provider: 'openai',
    displayName: 'GPT-4o',
    inputPerMTok: 2.5,
    outputPerMTok: 10,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-05-13',
  },
  {
    modelId: 'gpt-4o-mini',
    provider: 'openai',
    displayName: 'GPT-4o Mini',
    inputPerMTok: 0.15,
    outputPerMTok: 0.60,
    contextWindow: 128000,
    maxOutputTokens: 16384,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-07-18',
  },
  {
    modelId: 'o3',
    provider: 'openai',
    displayName: 'o3',
    inputPerMTok: 2,
    outputPerMTok: 8,
    contextWindow: 200000,
    maxOutputTokens: 100000,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-04-16',
  },
  {
    modelId: 'o4-mini',
    provider: 'openai',
    displayName: 'o4-mini',
    inputPerMTok: 1.10,
    outputPerMTok: 4.40,
    contextWindow: 200000,
    maxOutputTokens: 100000,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-04-16',
  },
  {
    modelId: 'gpt-5.1',
    provider: 'openai',
    displayName: 'GPT-5.1',
    inputPerMTok: 1.25,
    outputPerMTok: 10,
    contextWindow: 400000,
    maxOutputTokens: 128000,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-11-13',
  },
  {
    modelId: 'o3-pro',
    provider: 'openai',
    displayName: 'o3 Pro',
    inputPerMTok: 20,
    outputPerMTok: 80,
    contextWindow: 200000,
    maxOutputTokens: 100000,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-06-10',
  },
  {
    modelId: 'o3-mini',
    provider: 'openai',
    displayName: 'o3 Mini',
    inputPerMTok: 1.10,
    outputPerMTok: 4.40,
    contextWindow: 200000,
    maxOutputTokens: 100000,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-01-31',
  },

  // Google
  {
    modelId: 'gemini-2.5-pro',
    provider: 'google',
    displayName: 'Gemini 2.5 Pro',
    inputPerMTok: 1.25,
    outputPerMTok: 10,
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-06-17',
  },
  {
    modelId: 'gemini-2.5-flash',
    provider: 'google',
    displayName: 'Gemini 2.5 Flash',
    inputPerMTok: 0.30,
    outputPerMTok: 2.50,
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-06-17',
  },
  {
    modelId: 'gemini-2.0-flash',
    provider: 'google',
    displayName: 'Gemini 2.0 Flash',
    inputPerMTok: 0.10,
    outputPerMTok: 0.40,
    contextWindow: 1048576,
    maxOutputTokens: 8192,
    source: 'seed',
    status: 'deprecated',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-02-05',
  },
  {
    modelId: 'gemini-2.0-flash-lite',
    provider: 'google',
    displayName: 'Gemini 2.0 Flash-Lite',
    inputPerMTok: 0.075,
    outputPerMTok: 0.30,
    contextWindow: 1048576,
    maxOutputTokens: 8192,
    source: 'seed',
    status: 'deprecated',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-02-25',
  },
  {
    modelId: 'gemini-2.5-flash-lite',
    provider: 'google',
    displayName: 'Gemini 2.5 Flash-Lite',
    inputPerMTok: 0.10,
    outputPerMTok: 0.40,
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-07-22',
  },
  {
    modelId: 'gemini-3.1-pro-preview',
    provider: 'google',
    displayName: 'Gemini 3.1 Pro Preview',
    inputPerMTok: 2,
    outputPerMTok: 12,
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    source: 'seed',
    status: 'preview',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2026-02-19',
  },
  {
    modelId: 'gemini-3.1-flash-lite-preview',
    provider: 'google',
    displayName: 'Gemini 3.1 Flash-Lite Preview',
    inputPerMTok: 0.25,
    outputPerMTok: 1.5,
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    source: 'seed',
    status: 'preview',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2026-03-03',
  },
  {
    modelId: 'gemini-3-pro-preview',
    provider: 'google',
    displayName: 'Gemini 3 Pro Preview',
    inputPerMTok: 2,
    outputPerMTok: 12,
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    source: 'seed',
    status: 'deprecated',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-11-18',
  },
  {
    modelId: 'gemini-3-flash-preview',
    provider: 'google',
    displayName: 'Gemini 3 Flash Preview',
    inputPerMTok: 0.50,
    outputPerMTok: 3,
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    source: 'seed',
    status: 'preview',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-12-17',
  },

  // DeepSeek
  {
    modelId: 'deepseek-chat',
    provider: 'deepseek',
    displayName: 'DeepSeek V3.2',
    inputPerMTok: 0.28,
    outputPerMTok: 0.42,
    contextWindow: 131072,
    maxOutputTokens: 8192,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-12-26',
  },
  {
    modelId: 'deepseek-reasoner',
    provider: 'deepseek',
    displayName: 'DeepSeek R1 (V3.2)',
    inputPerMTok: 0.28,
    outputPerMTok: 0.42,
    contextWindow: 131072,
    maxOutputTokens: 65536,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-01-20',
  },

  // xAI
  {
    modelId: 'grok-4',
    provider: 'xai',
    displayName: 'Grok 4',
    inputPerMTok: 3,
    outputPerMTok: 15,
    contextWindow: 256000,
    maxOutputTokens: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-07-09',
  },
  {
    modelId: 'grok-4.1-fast',
    provider: 'xai',
    displayName: 'Grok 4.1 Fast',
    inputPerMTok: 0.20,
    outputPerMTok: 0.50,
    contextWindow: 2000000,
    maxOutputTokens: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-11-19',
  },
  {
    modelId: 'grok-3',
    provider: 'xai',
    displayName: 'Grok 3',
    inputPerMTok: 3,
    outputPerMTok: 15,
    contextWindow: 131072,
    maxOutputTokens: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-04-09',
  },
  {
    modelId: 'grok-3-mini',
    provider: 'xai',
    displayName: 'Grok 3 Mini',
    inputPerMTok: 0.30,
    outputPerMTok: 0.50,
    contextWindow: 131072,
    maxOutputTokens: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-04-09',
  },

  // Mistral
  {
    modelId: 'mistral-large-3',
    provider: 'mistral',
    displayName: 'Mistral Large 3',
    inputPerMTok: 0.50,
    outputPerMTok: 1.50,
    contextWindow: 262000,
    maxOutputTokens: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-12-02',
  },
  {
    modelId: 'mistral-medium-3',
    provider: 'mistral',
    displayName: 'Mistral Medium 3',
    inputPerMTok: 0.40,
    outputPerMTok: 2,
    contextWindow: 131072,
    maxOutputTokens: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-05-07',
  },
  {
    modelId: 'codestral',
    provider: 'mistral',
    displayName: 'Codestral',
    inputPerMTok: 0.30,
    outputPerMTok: 0.90,
    contextWindow: 256000,
    maxOutputTokens: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-01-13',
  },
  {
    modelId: 'mistral-small-3.1',
    provider: 'mistral',
    displayName: 'Mistral Small 3.1',
    inputPerMTok: 0.35,
    outputPerMTok: 0.56,
    contextWindow: 128000,
    maxOutputTokens: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-03-17',
  },

  // Qwen
  {
    modelId: 'qwen3-max',
    provider: 'qwen',
    displayName: 'Qwen 3 Max',
    inputPerMTok: 1.20,
    outputPerMTok: 6.00,
    contextWindow: 262000,
    maxOutputTokens: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-09-05',
  },
  {
    modelId: 'qwq-32b',
    provider: 'qwen',
    displayName: 'QwQ 32B',
    inputPerMTok: 0.15,
    outputPerMTok: 0.40,
    contextWindow: 131072,
    maxOutputTokens: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-03-05',
  },

  // Cohere
  {
    modelId: 'command-r-plus',
    provider: 'cohere',
    displayName: 'Command R+',
    inputPerMTok: 2.50,
    outputPerMTok: 10.00,
    contextWindow: 128000,
    maxOutputTokens: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-08-15',
  },
  {
    modelId: 'command-r',
    provider: 'cohere',
    displayName: 'Command R',
    inputPerMTok: 0.15,
    outputPerMTok: 0.60,
    contextWindow: 128000,
    maxOutputTokens: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-08-15',
  },

  // AI21
  {
    modelId: 'jamba-large-1.7',
    provider: 'ai21',
    displayName: 'Jamba Large 1.7',
    inputPerMTok: 2.00,
    outputPerMTok: 8.00,
    contextWindow: 256000,
    maxOutputTokens: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-08-01',
  },
  {
    modelId: 'jamba-1.5-mini',
    provider: 'ai21',
    displayName: 'Jamba 1.5 Mini',
    inputPerMTok: 0.20,
    outputPerMTok: 0.40,
    contextWindow: 256000,
    maxOutputTokens: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-06-01',
  },

  // Amazon
  {
    modelId: 'amazon-nova-pro',
    provider: 'amazon',
    displayName: 'Nova Pro',
    inputPerMTok: 0.80,
    outputPerMTok: 3.20,
    contextWindow: 300000,
    maxOutputTokens: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-12-03',
  },
  {
    modelId: 'amazon-nova-lite',
    provider: 'amazon',
    displayName: 'Nova Lite',
    inputPerMTok: 0.06,
    outputPerMTok: 0.24,
    contextWindow: 300000,
    maxOutputTokens: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-12-03',
  },
  {
    modelId: 'amazon-nova-micro',
    provider: 'amazon',
    displayName: 'Nova Micro',
    inputPerMTok: 0.035,
    outputPerMTok: 0.14,
    contextWindow: 128000,
    maxOutputTokens: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-12-03',
  },
];
