import type { ImageModelPricing } from './types';

export const STATIC_IMAGE_PRICING: ImageModelPricing[] = [
  // OpenAI
  {
    modelId: 'dall-e-3-standard-1024',
    provider: 'openai',
    displayName: 'DALL-E 3 Standard 1024',
    pricePerImage: 0.040,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2023-10-01',
  },
  {
    modelId: 'dall-e-3-hd-1024',
    provider: 'openai',
    displayName: 'DALL-E 3 HD 1024',
    pricePerImage: 0.080,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'hd',
    maxResolution: null,
    supportedFormats: ['png'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2023-10-01',
  },
  {
    modelId: 'dall-e-3-standard-1792',
    provider: 'openai',
    displayName: 'DALL-E 3 Standard 1792',
    pricePerImage: 0.080,
    pricePerMegapixel: null,
    defaultResolution: '1024x1792',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2023-10-01',
  },
  {
    modelId: 'dall-e-3-hd-1792',
    provider: 'openai',
    displayName: 'DALL-E 3 HD 1792',
    pricePerImage: 0.120,
    pricePerMegapixel: null,
    defaultResolution: '1024x1792',
    qualityTier: 'hd',
    maxResolution: null,
    supportedFormats: ['png'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2023-10-01',
  },
  {
    modelId: 'dall-e-2-1024',
    provider: 'openai',
    displayName: 'DALL-E 2 1024',
    pricePerImage: 0.020,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2022-11-01',
  },
  {
    modelId: 'gpt-image-1-low',
    provider: 'openai',
    displayName: 'GPT Image 1 Low',
    pricePerImage: 0.011,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png', 'webp'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-04-23',
  },
  {
    modelId: 'gpt-image-1-medium',
    provider: 'openai',
    displayName: 'GPT Image 1 Medium',
    pricePerImage: 0.042,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png', 'webp'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-04-23',
  },
  {
    modelId: 'gpt-image-1-high',
    provider: 'openai',
    displayName: 'GPT Image 1 High',
    pricePerImage: 0.167,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'hd',
    maxResolution: null,
    supportedFormats: ['png', 'webp'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-04-23',
  },

  // Google
  {
    modelId: 'imagen-3',
    provider: 'google',
    displayName: 'Imagen 3',
    pricePerImage: 0.04,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-08-01',
  },
  {
    modelId: 'imagen-4-fast',
    provider: 'google',
    displayName: 'Imagen 4 Fast',
    pricePerImage: 0.02,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-05-01',
  },
  {
    modelId: 'imagen-4-standard',
    provider: 'google',
    displayName: 'Imagen 4 Standard',
    pricePerImage: 0.04,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-05-01',
  },
  {
    modelId: 'imagen-4-ultra',
    provider: 'google',
    displayName: 'Imagen 4 Ultra',
    pricePerImage: 0.06,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'hd',
    maxResolution: null,
    supportedFormats: ['png'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-05-01',
  },

  // Stability AI
  {
    modelId: 'sd-3.5-large',
    provider: 'stability',
    displayName: 'SD 3.5 Large',
    pricePerImage: 0.065,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png', 'webp'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-10-22',
  },
  {
    modelId: 'sd-3.5-large-turbo',
    provider: 'stability',
    displayName: 'SD 3.5 Large Turbo',
    pricePerImage: 0.04,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png', 'webp'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-10-22',
  },
  {
    modelId: 'stable-image-ultra',
    provider: 'stability',
    displayName: 'Stable Image Ultra',
    pricePerImage: 0.08,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'ultra',
    maxResolution: null,
    supportedFormats: ['png', 'webp'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-04-01',
  },
  {
    modelId: 'stable-image-core',
    provider: 'stability',
    displayName: 'Stable Image Core',
    pricePerImage: 0.03,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png', 'webp'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-04-01',
  },

  // Black Forest Labs — FLUX.1 series
  {
    modelId: 'flux-1.1-pro',
    provider: 'bfl',
    displayName: 'FLUX 1.1 Pro',
    pricePerImage: 0.04,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png', 'jpeg'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-10-02',
  },
  {
    modelId: 'flux-1.1-pro-ultra',
    provider: 'bfl',
    displayName: 'FLUX 1.1 Pro Ultra',
    pricePerImage: 0.06,
    pricePerMegapixel: null,
    defaultResolution: '2048x2048',
    qualityTier: 'hd',
    maxResolution: '2048x2048',
    supportedFormats: ['png', 'jpeg'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-11-06',
  },
  {
    modelId: 'flux-1.1-pro-raw',
    provider: 'bfl',
    displayName: 'FLUX 1.1 Pro Raw',
    pricePerImage: 0.06,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png', 'jpeg'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-11-06',
  },
  {
    modelId: 'flux-1-kontext-pro',
    provider: 'bfl',
    displayName: 'FLUX 1 Kontext Pro',
    pricePerImage: 0.04,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png', 'jpeg'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-05-29',
  },
  {
    modelId: 'flux-1-kontext-max',
    provider: 'bfl',
    displayName: 'FLUX 1 Kontext Max',
    pricePerImage: 0.08,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'hd',
    maxResolution: null,
    supportedFormats: ['png', 'jpeg'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-05-29',
  },
  {
    modelId: 'flux-1-fill-pro',
    provider: 'bfl',
    displayName: 'FLUX 1 Fill Pro',
    pricePerImage: 0.05,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png', 'jpeg'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-11-01',
  },
  // Black Forest Labs — FLUX.2 series (megapixel-based, price = first MP flat rate)
  {
    modelId: 'flux-2-klein-4b',
    provider: 'bfl',
    displayName: 'FLUX 2 Klein 4B',
    pricePerImage: 0.014,
    pricePerMegapixel: 0.001,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png', 'jpeg'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2026-01-15',
  },
  {
    modelId: 'flux-2-klein-9b',
    provider: 'bfl',
    displayName: 'FLUX 2 Klein 9B',
    pricePerImage: 0.015,
    pricePerMegapixel: 0.001,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png', 'jpeg'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2026-01-15',
  },
  {
    modelId: 'flux-2-pro',
    provider: 'bfl',
    displayName: 'FLUX 2 Pro',
    pricePerImage: 0.03,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png', 'jpeg'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-11-25',
  },
  {
    modelId: 'flux-2-flex',
    provider: 'bfl',
    displayName: 'FLUX 2 Flex',
    pricePerImage: 0.05,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png', 'jpeg'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-11-25',
  },

  // Recraft
  {
    modelId: 'recraft-v4-raster',
    provider: 'recraft',
    displayName: 'Recraft V4 Raster',
    pricePerImage: 0.04,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png', 'svg'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-01-15',
  },
  {
    modelId: 'recraft-v4-vector',
    provider: 'recraft',
    displayName: 'Recraft V4 Vector',
    pricePerImage: 0.08,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['svg'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-01-15',
  },

  // Bytedance
  {
    modelId: 'seedream-4.5',
    provider: 'bytedance',
    displayName: 'Seedream 4.5',
    pricePerImage: 0.035,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-01-15',
  },

  // fal.ai — FLUX models
  {
    modelId: 'fal-flux-1-schnell',
    provider: 'fal',
    displayName: 'fal FLUX.1 Schnell',
    pricePerImage: 0.003,
    pricePerMegapixel: 0.003,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png', 'jpeg'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-08-01',
  },
  {
    modelId: 'fal-flux-1-dev',
    provider: 'fal',
    displayName: 'fal FLUX.1 Dev',
    pricePerImage: 0.025,
    pricePerMegapixel: 0.025,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png', 'jpeg'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-08-01',
  },
  {
    modelId: 'fal-flux-1-pro',
    provider: 'fal',
    displayName: 'fal FLUX.1 Pro',
    pricePerImage: 0.04,
    pricePerMegapixel: 0.04,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png', 'jpeg'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-08-01',
  },
  {
    modelId: 'fal-flux-2-pro',
    provider: 'fal',
    displayName: 'fal FLUX.2 Pro',
    pricePerImage: 0.03,
    pricePerMegapixel: 0.015,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png', 'jpeg'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-11-25',
  },
  {
    modelId: 'fal-flux-2-flex',
    provider: 'fal',
    displayName: 'fal FLUX.2 Flex',
    pricePerImage: 0.05,
    pricePerMegapixel: 0.05,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png', 'jpeg'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-11-25',
  },
  {
    modelId: 'fal-flux-1-kontext-pro',
    provider: 'fal',
    displayName: 'fal FLUX.1 Kontext Pro',
    pricePerImage: 0.04,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png', 'jpeg'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-05-29',
  },
  // fal.ai — third-party models
  {
    modelId: 'fal-recraft-v3',
    provider: 'fal',
    displayName: 'fal Recraft V3',
    pricePerImage: 0.04,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-11-01',
  },
  {
    modelId: 'fal-recraft-v4-pro',
    provider: 'fal',
    displayName: 'fal Recraft V4 Pro',
    pricePerImage: 0.25,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'hd',
    maxResolution: null,
    supportedFormats: ['png', 'svg'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-01-15',
  },
  {
    modelId: 'fal-ideogram-v3',
    provider: 'fal',
    displayName: 'fal Ideogram V3',
    pricePerImage: 0.06,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-06-01',
  },
  {
    modelId: 'fal-ideogram-v2',
    provider: 'fal',
    displayName: 'fal Ideogram V2',
    pricePerImage: 0.08,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-01-15',
  },
  {
    modelId: 'fal-sd3',
    provider: 'fal',
    displayName: 'fal SD3',
    pricePerImage: 0.035,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-01-15',
  },
  {
    modelId: 'fal-nano-banana-2',
    provider: 'fal',
    displayName: 'fal Nano Banana 2',
    pricePerImage: 0.08,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: '4096x4096',
    supportedFormats: ['png', 'jpeg'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-12-01',
  },
  {
    modelId: 'fal-nano-banana-pro',
    provider: 'fal',
    displayName: 'fal Nano Banana Pro',
    pricePerImage: 0.15,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'hd',
    maxResolution: '4096x4096',
    supportedFormats: ['png', 'jpeg'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-12-01',
  },
  {
    modelId: 'fal-qwen-image-2-pro',
    provider: 'fal',
    displayName: 'fal Qwen Image 2.0 Pro',
    pricePerImage: 0.075,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-10-01',
  },

  // Ideogram
  {
    modelId: 'ideogram-v3',
    provider: 'ideogram',
    displayName: 'Ideogram V3',
    pricePerImage: 0.024,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-01-15',
  },
  {
    modelId: 'ideogram-v3-turbo',
    provider: 'ideogram',
    displayName: 'Ideogram V3 Turbo',
    pricePerImage: 0.008,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-01-15',
  },

  // xAI
  {
    modelId: 'aurora-grok-2-image',
    provider: 'xai',
    displayName: 'Aurora Grok 2 Image',
    pricePerImage: 0.07,
    pricePerMegapixel: null,
    defaultResolution: '1024x1024',
    qualityTier: 'standard',
    maxResolution: null,
    supportedFormats: ['png'],
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-01-15',
  },
];
