import type { ModelPricing } from './types';

export const STATIC_PRICING: ModelPricing[] = [
  // Anthropic
  {
    modelId: 'claude-opus-4-6',
    provider: 'anthropic',
    displayName: 'Claude Opus 4.6',
    inputPerMTok: 15,
    outputPerMTok: 75,
    contextWindow: 200000,
    maxOutputTokens: 32000,
    source: 'seed',
    lastUpdated: null,
  },
  {
    modelId: 'claude-sonnet-4-6',
    provider: 'anthropic',
    displayName: 'Claude Sonnet 4.6',
    inputPerMTok: 3,
    outputPerMTok: 15,
    contextWindow: 200000,
    maxOutputTokens: 64000,
    source: 'seed',
    lastUpdated: null,
  },
  {
    modelId: 'claude-haiku-4-5-20251001',
    provider: 'anthropic',
    displayName: 'Claude Haiku 4.5',
    inputPerMTok: 0.80,
    outputPerMTok: 4,
    contextWindow: 200000,
    maxOutputTokens: 8192,
    source: 'seed',
    lastUpdated: null,
  },

  // OpenAI
  {
    modelId: 'gpt-4.1',
    provider: 'openai',
    displayName: 'GPT-4.1',
    inputPerMTok: 2,
    outputPerMTok: 8,
    contextWindow: 1047576,
    maxOutputTokens: 32768,
    source: 'seed',
    lastUpdated: null,
  },
  {
    modelId: 'gpt-4.1-mini',
    provider: 'openai',
    displayName: 'GPT-4.1 Mini',
    inputPerMTok: 0.40,
    outputPerMTok: 1.60,
    contextWindow: 1047576,
    maxOutputTokens: 32768,
    source: 'seed',
    lastUpdated: null,
  },
  {
    modelId: 'gpt-4.1-nano',
    provider: 'openai',
    displayName: 'GPT-4.1 Nano',
    inputPerMTok: 0.10,
    outputPerMTok: 0.40,
    contextWindow: 1047576,
    maxOutputTokens: 32768,
    source: 'seed',
    lastUpdated: null,
  },
  {
    modelId: 'o3',
    provider: 'openai',
    displayName: 'o3',
    inputPerMTok: 2,
    outputPerMTok: 8,
    contextWindow: 200000,
    maxOutputTokens: 100000,
    source: 'seed',
    lastUpdated: null,
  },
  {
    modelId: 'o4-mini',
    provider: 'openai',
    displayName: 'o4-mini',
    inputPerMTok: 1.10,
    outputPerMTok: 4.40,
    contextWindow: 200000,
    maxOutputTokens: 100000,
    source: 'seed',
    lastUpdated: null,
  },

  // Google
  {
    modelId: 'gemini-2.5-pro',
    provider: 'google',
    displayName: 'Gemini 2.5 Pro',
    inputPerMTok: 1.25,
    outputPerMTok: 10,
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    source: 'seed',
    lastUpdated: null,
  },
  {
    modelId: 'gemini-2.5-flash',
    provider: 'google',
    displayName: 'Gemini 2.5 Flash',
    inputPerMTok: 0.15,
    outputPerMTok: 0.60,
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    source: 'seed',
    lastUpdated: null,
  },
  {
    modelId: 'gemini-2.0-flash',
    provider: 'google',
    displayName: 'Gemini 2.0 Flash',
    inputPerMTok: 0.10,
    outputPerMTok: 0.40,
    contextWindow: 1048576,
    maxOutputTokens: 8192,
    source: 'seed',
    lastUpdated: null,
  },
  {
    modelId: 'gemini-2.0-flash-lite',
    provider: 'google',
    displayName: 'Gemini 2.0 Flash-Lite',
    inputPerMTok: 0.075,
    outputPerMTok: 0.30,
    contextWindow: 1048576,
    maxOutputTokens: 8192,
    source: 'seed',
    lastUpdated: null,
  },

  // DeepSeek
  {
    modelId: 'deepseek-chat',
    provider: 'deepseek',
    displayName: 'DeepSeek V3',
    inputPerMTok: 0.27,
    outputPerMTok: 1.10,
    contextWindow: 65536,
    maxOutputTokens: 8192,
    source: 'seed',
    lastUpdated: null,
  },
  {
    modelId: 'deepseek-reasoner',
    provider: 'deepseek',
    displayName: 'DeepSeek R1',
    inputPerMTok: 0.55,
    outputPerMTok: 2.19,
    contextWindow: 65536,
    maxOutputTokens: 8192,
    source: 'seed',
    lastUpdated: null,
  },
];
