import type { SttModelPricing } from './types';

export const STATIC_STT_PRICING: SttModelPricing[] = [
  // OpenAI — Whisper
  {
    modelId: 'openai-whisper-1',
    provider: 'openai',
    displayName: 'OpenAI Whisper',
    costPerMinute: 0.006,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2023-03-01',
  },
  // OpenAI — GPT-4o Transcribe
  {
    modelId: 'openai-gpt4o-transcribe',
    provider: 'openai',
    displayName: 'OpenAI GPT-4o Transcribe',
    costPerMinute: 0.006,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-03-01',
  },
  // OpenAI — GPT-4o Mini Transcribe
  {
    modelId: 'openai-gpt4o-mini-transcribe',
    provider: 'openai',
    displayName: 'OpenAI GPT-4o Mini Transcribe',
    costPerMinute: 0.003,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-03-01',
  },
  // Deepgram — Nova-3
  {
    modelId: 'deepgram-nova-3',
    provider: 'deepgram',
    displayName: 'Deepgram Nova-3',
    costPerMinute: 0.0077,
    sttType: 'streaming',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-01-01',
  },
  // Deepgram — Nova-3 Multilingual
  {
    modelId: 'deepgram-nova-3-multilingual',
    provider: 'deepgram',
    displayName: 'Deepgram Nova-3 Multilingual',
    costPerMinute: 0.0092,
    sttType: 'streaming',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-01-01',
  },
  // Deepgram — Nova-2
  {
    modelId: 'deepgram-nova-2',
    provider: 'deepgram',
    displayName: 'Deepgram Nova-2',
    costPerMinute: 0.0058,
    sttType: 'streaming',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2023-12-01',
  },
  // AssemblyAI — Universal-2
  {
    modelId: 'assemblyai-universal-2',
    provider: 'assemblyai',
    displayName: 'AssemblyAI Universal-2',
    costPerMinute: 0.0025,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-06-01',
  },
  // Google Cloud — STT Standard
  {
    modelId: 'google-cloud-stt-standard',
    provider: 'google-cloud',
    displayName: 'Google Cloud STT Standard',
    costPerMinute: 0.024,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2018-04-01',
  },
  // Google Cloud — STT Enhanced
  {
    modelId: 'google-cloud-stt-enhanced',
    provider: 'google-cloud',
    displayName: 'Google Cloud STT Enhanced',
    costPerMinute: 0.036,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2018-04-01',
  },
  // Azure — STT Standard
  {
    modelId: 'azure-stt-standard',
    provider: 'azure',
    displayName: 'Azure STT Standard',
    costPerMinute: 0.017,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2019-09-01',
  },
];
