import type { SttModelPricing } from './types';

export const STATIC_STT_PRICING: SttModelPricing[] = [
  // OpenAI — Whisper
  {
    modelId: 'openai-whisper-1',
    provider: 'openai',
    displayName: 'OpenAI Whisper',
    costPerMinute: 0.006,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2023-03-01',
  },
  // OpenAI — GPT-4o Transcribe
  {
    modelId: 'openai-gpt4o-transcribe',
    provider: 'openai',
    displayName: 'OpenAI GPT-4o Transcribe',
    costPerMinute: 0.006,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-03-01',
  },
  // OpenAI — GPT-4o Mini Transcribe
  {
    modelId: 'openai-gpt4o-mini-transcribe',
    provider: 'openai',
    displayName: 'OpenAI GPT-4o Mini Transcribe',
    costPerMinute: 0.003,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-03-01',
  },
  // Deepgram — Nova-3
  {
    modelId: 'deepgram-nova-3',
    provider: 'deepgram',
    displayName: 'Deepgram Nova-3',
    costPerMinute: 0.0077,
    sttType: 'streaming',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-01-01',
  },
  // Deepgram — Nova-3 Multilingual
  {
    modelId: 'deepgram-nova-3-multilingual',
    provider: 'deepgram',
    displayName: 'Deepgram Nova-3 Multilingual',
    costPerMinute: 0.0092,
    sttType: 'streaming',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-01-01',
  },
  // Deepgram — Nova-2
  {
    modelId: 'deepgram-nova-2',
    provider: 'deepgram',
    displayName: 'Deepgram Nova-2',
    costPerMinute: 0.0058,
    sttType: 'streaming',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2023-12-01',
  },
  // AssemblyAI — Universal-2
  {
    modelId: 'assemblyai-universal-2',
    provider: 'assemblyai',
    displayName: 'AssemblyAI Universal-2',
    costPerMinute: 0.0025,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-06-01',
  },
  // Google Cloud — STT Standard
  {
    modelId: 'google-cloud-stt-standard',
    provider: 'google-cloud',
    displayName: 'Google Cloud STT Standard',
    costPerMinute: 0.024,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2018-04-01',
  },
  // Google Cloud — STT Enhanced
  {
    modelId: 'google-cloud-stt-enhanced',
    provider: 'google-cloud',
    displayName: 'Google Cloud STT Enhanced',
    costPerMinute: 0.036,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2018-04-01',
  },
  // Azure — STT Standard
  {
    modelId: 'azure-stt-standard',
    provider: 'azure',
    displayName: 'Azure STT Standard',
    costPerMinute: 0.017,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2019-09-01',
  },
  // ElevenLabs — Scribe v1
  {
    modelId: 'elevenlabs-scribe-v1',
    provider: 'elevenlabs',
    displayName: 'ElevenLabs Scribe v1',
    costPerMinute: 0.0067,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-02-01',
  },
  // ElevenLabs — Scribe v2
  {
    modelId: 'elevenlabs-scribe-v2',
    provider: 'elevenlabs',
    displayName: 'ElevenLabs Scribe v2',
    costPerMinute: 0.0067,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-06-01',
  },
  // ElevenLabs — Scribe v2 Realtime
  {
    modelId: 'elevenlabs-scribe-v2-realtime',
    provider: 'elevenlabs',
    displayName: 'ElevenLabs Scribe v2 Realtime',
    costPerMinute: 0.008,
    sttType: 'streaming',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-09-01',
  },
  // Cartesia — Ink
  {
    modelId: 'cartesia-ink',
    provider: 'cartesia',
    displayName: 'Cartesia Ink',
    costPerMinute: 0.017,
    sttType: 'streaming',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-03-01',
  },
  // --- Models matching DB modelIds (for backfill) ---
  // AssemblyAI
  {
    modelId: 'assemblyai-universal-2-batch',
    provider: 'assemblyai',
    displayName: 'AssemblyAI Universal-2 (Pre-recorded)',
    costPerMinute: 0.0025,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-10-31',
  },
  {
    modelId: 'assemblyai-universal-3-pro-batch',
    provider: 'assemblyai',
    displayName: 'AssemblyAI Universal-3 Pro (Pre-recorded)',
    costPerMinute: 0.005,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2026-02-03',
  },
  {
    modelId: 'assemblyai-universal-3-pro-streaming',
    provider: 'assemblyai',
    displayName: 'AssemblyAI Universal-3 Pro Streaming',
    costPerMinute: 0.007,
    sttType: 'streaming',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2026-03-03',
  },
  {
    modelId: 'assemblyai-universal-streaming-en',
    provider: 'assemblyai',
    displayName: 'AssemblyAI Universal-Streaming (English)',
    costPerMinute: 0.004,
    sttType: 'streaming',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-06-02',
  },
  {
    modelId: 'assemblyai-universal-streaming-multilingual',
    provider: 'assemblyai',
    displayName: 'AssemblyAI Universal-Streaming Multilingual',
    costPerMinute: 0.006,
    sttType: 'streaming',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-11-12',
  },
  {
    modelId: 'assemblyai-whisper-streaming',
    provider: 'assemblyai',
    displayName: 'AssemblyAI Whisper Streaming',
    costPerMinute: 0.004,
    sttType: 'streaming',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-11-01',
  },
  // Azure Speech
  {
    modelId: 'azure-speech-custom-batch',
    provider: 'azure',
    displayName: 'Azure Speech Custom Batch Transcription',
    costPerMinute: 0.025,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2018-09-24',
  },
  {
    modelId: 'azure-speech-custom-realtime',
    provider: 'azure',
    displayName: 'Azure Speech Custom Real-time Transcription',
    costPerMinute: 0.025,
    sttType: 'real-time',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2018-09-24',
  },
  {
    modelId: 'azure-speech-standard-batch',
    provider: 'azure',
    displayName: 'Azure Speech Standard Batch Transcription',
    costPerMinute: 0.017,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2018-09-24',
  },
  {
    modelId: 'azure-speech-standard-realtime',
    provider: 'azure',
    displayName: 'Azure Speech Standard Real-time Transcription',
    costPerMinute: 0.017,
    sttType: 'real-time',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2018-09-24',
  },
  // Cartesia
  {
    modelId: 'cartesia-ink-whisper',
    provider: 'cartesia',
    displayName: 'Cartesia Ink-Whisper',
    costPerMinute: 0.017,
    sttType: 'streaming',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-06-10',
  },
  {
    modelId: 'cartesia-ink-whisper-standard',
    provider: 'cartesia',
    displayName: 'Cartesia Ink-Whisper',
    costPerMinute: 0.017,
    sttType: 'streaming',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-06-10',
  },
  // Deepgram — Base
  {
    modelId: 'deepgram-base-batch',
    provider: 'deepgram',
    displayName: 'Deepgram Base (Pre-Recorded)',
    costPerMinute: 0.0044,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2022-07-07',
  },
  {
    modelId: 'deepgram-base-prerecorded',
    provider: 'deepgram',
    displayName: 'Deepgram Base (Pre-Recorded)',
    costPerMinute: 0.0044,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2022-07-07',
  },
  {
    modelId: 'deepgram-base-streaming',
    provider: 'deepgram',
    displayName: 'Deepgram Base (Streaming)',
    costPerMinute: 0.0055,
    sttType: 'streaming',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2022-07-07',
  },
  // Deepgram — Enhanced
  {
    modelId: 'deepgram-enhanced-batch',
    provider: 'deepgram',
    displayName: 'Deepgram Enhanced (Pre-Recorded)',
    costPerMinute: 0.0044,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2022-05-26',
  },
  {
    modelId: 'deepgram-enhanced-prerecorded',
    provider: 'deepgram',
    displayName: 'Deepgram Enhanced (Pre-Recorded)',
    costPerMinute: 0.0044,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2022-05-26',
  },
  {
    modelId: 'deepgram-enhanced-streaming',
    provider: 'deepgram',
    displayName: 'Deepgram Enhanced (Streaming)',
    costPerMinute: 0.0055,
    sttType: 'streaming',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2022-05-26',
  },
  // Deepgram — Flux
  {
    modelId: 'deepgram-flux-batch',
    provider: 'deepgram',
    displayName: 'Deepgram Flux (Pre-Recorded)',
    costPerMinute: 0.0059,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-10-02',
  },
  {
    modelId: 'deepgram-flux-prerecorded',
    provider: 'deepgram',
    displayName: 'Deepgram Flux (Pre-Recorded)',
    costPerMinute: 0.0059,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-10-02',
  },
  {
    modelId: 'deepgram-flux-streaming',
    provider: 'deepgram',
    displayName: 'Deepgram Flux (Streaming)',
    costPerMinute: 0.007,
    sttType: 'streaming',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-10-02',
  },
  // Deepgram — Nova-2
  {
    modelId: 'deepgram-nova-2-batch',
    provider: 'deepgram',
    displayName: 'Deepgram Nova-1 & 2 (Pre-Recorded)',
    costPerMinute: 0.0044,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2023-11-14',
  },
  {
    modelId: 'deepgram-nova-2-prerecorded',
    provider: 'deepgram',
    displayName: 'Deepgram Nova-1 & 2 (Pre-Recorded)',
    costPerMinute: 0.0044,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2023-11-14',
  },
  {
    modelId: 'deepgram-nova-2-streaming',
    provider: 'deepgram',
    displayName: 'Deepgram Nova-1 & 2 (Streaming)',
    costPerMinute: 0.0058,
    sttType: 'streaming',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2023-11-14',
  },
  // Deepgram — Nova-3 Monolingual
  {
    modelId: 'deepgram-nova-3-monolingual-batch',
    provider: 'deepgram',
    displayName: 'Deepgram Nova-3 Monolingual (Pre-Recorded)',
    costPerMinute: 0.0059,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-02-12',
  },
  {
    modelId: 'deepgram-nova-3-monolingual-prerecorded',
    provider: 'deepgram',
    displayName: 'Deepgram Nova-3 Monolingual',
    costPerMinute: 0.0059,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-02-12',
  },
  {
    modelId: 'deepgram-nova-3-monolingual-streaming',
    provider: 'deepgram',
    displayName: 'Deepgram Nova-3 Monolingual (Streaming)',
    costPerMinute: 0.0077,
    sttType: 'streaming',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-02-12',
  },
  // Deepgram — Nova-3 Multilingual
  {
    modelId: 'deepgram-nova-3-multilingual-batch',
    provider: 'deepgram',
    displayName: 'Deepgram Nova-3 Multilingual (Pre-Recorded)',
    costPerMinute: 0.007,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-02-12',
  },
  {
    modelId: 'deepgram-nova-3-multilingual-prerecorded',
    provider: 'deepgram',
    displayName: 'Deepgram Nova-3 Multilingual',
    costPerMinute: 0.007,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-02-12',
  },
  {
    modelId: 'deepgram-nova-3-multilingual-streaming',
    provider: 'deepgram',
    displayName: 'Deepgram Nova-3 Multilingual (Streaming)',
    costPerMinute: 0.0092,
    sttType: 'streaming',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-02-12',
  },
  // Google Cloud STT V1
  {
    modelId: 'google-cloud-stt-v1-medical-conversation',
    provider: 'google-cloud',
    displayName: 'Google Cloud Speech-to-Text V1 Medical Conversation',
    costPerMinute: 0.078,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2021-11-08',
  },
  {
    modelId: 'google-cloud-stt-v1-medical-dictation',
    provider: 'google-cloud',
    displayName: 'Google Cloud Speech-to-Text V1 Medical Dictation',
    costPerMinute: 0.078,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2021-11-08',
  },
  {
    modelId: 'google-cloud-stt-v1-standard-logged',
    provider: 'google-cloud',
    displayName: 'Google Cloud Speech-to-Text V1 Standard (with data logging)',
    costPerMinute: 0.016,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2017-04-18',
  },
  {
    modelId: 'google-cloud-stt-v1-standard-unlogged',
    provider: 'google-cloud',
    displayName: 'Google Cloud Speech-to-Text V1 Standard (without data logging)',
    costPerMinute: 0.024,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2017-04-18',
  },
  {
    modelId: 'google-cloud-stt-v1-standard-with-logging',
    provider: 'google-cloud',
    displayName: 'Google Cloud Speech-to-Text V1 Standard (with data logging)',
    costPerMinute: 0.016,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2017-04-18',
  },
  {
    modelId: 'google-cloud-stt-v1-standard-without-logging',
    provider: 'google-cloud',
    displayName: 'Google Cloud Speech-to-Text V1 Standard (without data logging)',
    costPerMinute: 0.024,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2017-04-18',
  },
  // Google Cloud STT V2
  {
    modelId: 'google-cloud-stt-v2-dynamic-batch',
    provider: 'google-cloud',
    displayName: 'Google Cloud Speech-to-Text V2 Dynamic Batch',
    costPerMinute: 0.016,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2023-08-09',
  },
  {
    modelId: 'google-cloud-stt-v2-standard',
    provider: 'google-cloud',
    displayName: 'Google Cloud Speech-to-Text V2 Standard (0–500k min)',
    costPerMinute: 0.016,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2023-08-09',
  },
  {
    modelId: 'google-cloud-stt-v2-standard-tier2',
    provider: 'google-cloud',
    displayName: 'Google Cloud Speech-to-Text V2 Standard (500k–1M min)',
    costPerMinute: 0.012,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2023-08-09',
  },
  {
    modelId: 'google-cloud-stt-v2-standard-tier3',
    provider: 'google-cloud',
    displayName: 'Google Cloud Speech-to-Text V2 Standard (1M–2M min)',
    costPerMinute: 0.008,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2023-08-09',
  },
  {
    modelId: 'google-cloud-stt-v2-standard-tier4',
    provider: 'google-cloud',
    displayName: 'Google Cloud Speech-to-Text V2 Standard (2M+ min)',
    costPerMinute: 0.006,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2023-08-09',
  },
  // OpenAI
  {
    modelId: 'openai-gpt-4o-mini-transcribe',
    provider: 'openai',
    displayName: 'OpenAI GPT-4o Mini Transcribe',
    costPerMinute: 0.003,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-03-20',
  },
  {
    modelId: 'openai-gpt-4o-transcribe',
    provider: 'openai',
    displayName: 'OpenAI GPT-4o Transcribe',
    costPerMinute: 0.006,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-03-20',
  },
  {
    modelId: 'openai-gpt-4o-transcribe-diarize',
    provider: 'openai',
    displayName: 'OpenAI GPT-4o Transcribe (Diarize)',
    costPerMinute: 0.006,
    sttType: 'batch',
    maxDuration: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-10-18',
  },
];
