import type { TtsModelPricing } from './types';

export const STATIC_TTS_PRICING: TtsModelPricing[] = [
  // OpenAI — TTS Standard
  {
    modelId: 'openai-tts-1',
    provider: 'openai',
    displayName: 'OpenAI TTS Standard',
    costPerMChars: 15.0,
    voiceType: 'standard',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2023-11-06',
  },
  // OpenAI — TTS HD
  {
    modelId: 'openai-tts-1-hd',
    provider: 'openai',
    displayName: 'OpenAI TTS HD',
    costPerMChars: 30.0,
    voiceType: 'hd',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2023-11-06',
  },
  // Google Cloud — TTS Standard
  {
    modelId: 'google-cloud-tts-standard',
    provider: 'google-cloud',
    displayName: 'Google Cloud TTS Standard',
    costPerMChars: 4.0,
    voiceType: 'standard',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2018-03-27',
  },
  // Google Cloud — TTS WaveNet
  {
    modelId: 'google-cloud-tts-wavenet',
    provider: 'google-cloud',
    displayName: 'Google Cloud TTS WaveNet',
    costPerMChars: 16.0,
    voiceType: 'wavenet',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2018-03-27',
  },
  // Google Cloud — TTS Neural2
  {
    modelId: 'google-cloud-tts-neural2',
    provider: 'google-cloud',
    displayName: 'Google Cloud TTS Neural2',
    costPerMChars: 16.0,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2022-06-01',
  },
  // Amazon — Polly Standard
  {
    modelId: 'amazon-polly-standard',
    provider: 'amazon',
    displayName: 'Amazon Polly Standard',
    costPerMChars: 4.0,
    voiceType: 'standard',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2016-11-30',
  },
  // Amazon — Polly Neural
  {
    modelId: 'amazon-polly-neural',
    provider: 'amazon',
    displayName: 'Amazon Polly Neural',
    costPerMChars: 16.0,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2019-07-30',
  },
  // Azure — TTS Neural
  {
    modelId: 'azure-tts-neural',
    provider: 'azure',
    displayName: 'Azure TTS Neural',
    costPerMChars: 16.0,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2019-09-01',
  },
  // Azure — TTS HD V2
  {
    modelId: 'azure-tts-hd-v2',
    provider: 'azure',
    displayName: 'Azure TTS HD V2',
    costPerMChars: 30.0,
    voiceType: 'hd',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-06-01',
  },
  // ElevenLabs — Standard
  {
    modelId: 'elevenlabs-standard',
    provider: 'elevenlabs',
    displayName: 'ElevenLabs Standard',
    costPerMChars: 30.0,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2023-01-01',
  },
  // Deepgram — Aura-1
  {
    modelId: 'deepgram-aura-1',
    provider: 'deepgram',
    displayName: 'Deepgram Aura-1',
    costPerMChars: 15.0,
    voiceType: 'standard',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-01-01',
  },
  // Deepgram — Aura-2
  {
    modelId: 'deepgram-aura-2',
    provider: 'deepgram',
    displayName: 'Deepgram Aura-2',
    costPerMChars: 30.0,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-01-01',
  },
  // PlayHT — 2.0
  {
    modelId: 'playht-2',
    provider: 'playht',
    displayName: 'PlayHT 2.0',
    costPerMChars: 30.0,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2023-06-01',
  },
];
