import type { TtsModelPricing } from './types';

export const STATIC_TTS_PRICING: TtsModelPricing[] = [
  // OpenAI — TTS Standard
  {
    modelId: 'openai-tts-1',
    provider: 'openai',
    displayName: 'OpenAI TTS Standard',
    costPerMChars: 15.0,
    voiceType: 'standard',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2023-11-06',
  },
  // OpenAI — TTS HD
  {
    modelId: 'openai-tts-1-hd',
    provider: 'openai',
    displayName: 'OpenAI TTS HD',
    costPerMChars: 30.0,
    voiceType: 'hd',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2023-11-06',
  },
  // Google Cloud — TTS Standard
  {
    modelId: 'google-cloud-tts-standard',
    provider: 'google-cloud',
    displayName: 'Google Cloud TTS Standard',
    costPerMChars: 4.0,
    voiceType: 'standard',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2018-03-27',
  },
  // Google Cloud — TTS WaveNet
  {
    modelId: 'google-cloud-tts-wavenet',
    provider: 'google-cloud',
    displayName: 'Google Cloud TTS WaveNet',
    costPerMChars: 16.0,
    voiceType: 'wavenet',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2018-03-27',
  },
  // Google Cloud — TTS Neural2
  {
    modelId: 'google-cloud-tts-neural2',
    provider: 'google-cloud',
    displayName: 'Google Cloud TTS Neural2',
    costPerMChars: 16.0,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2022-06-01',
  },
  // Amazon — Polly Standard
  {
    modelId: 'amazon-polly-standard',
    provider: 'amazon',
    displayName: 'Amazon Polly Standard',
    costPerMChars: 4.0,
    voiceType: 'standard',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2016-11-30',
  },
  // Amazon — Polly Neural
  {
    modelId: 'amazon-polly-neural',
    provider: 'amazon',
    displayName: 'Amazon Polly Neural',
    costPerMChars: 16.0,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2019-07-30',
  },
  // Azure — TTS Neural
  {
    modelId: 'azure-tts-neural',
    provider: 'azure',
    displayName: 'Azure TTS Neural',
    costPerMChars: 16.0,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2019-09-01',
  },
  // Azure — TTS HD V2
  {
    modelId: 'azure-tts-hd-v2',
    provider: 'azure',
    displayName: 'Azure TTS HD V2',
    costPerMChars: 30.0,
    voiceType: 'hd',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-06-01',
  },
  // ElevenLabs — Standard
  {
    modelId: 'elevenlabs-standard',
    provider: 'elevenlabs',
    displayName: 'ElevenLabs Standard',
    costPerMChars: 30.0,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2023-01-01',
  },
  // Deepgram — Aura-1
  {
    modelId: 'deepgram-aura-1',
    provider: 'deepgram',
    displayName: 'Deepgram Aura-1',
    costPerMChars: 15.0,
    voiceType: 'standard',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-01-01',
  },
  // Deepgram — Aura-2
  {
    modelId: 'deepgram-aura-2',
    provider: 'deepgram',
    displayName: 'Deepgram Aura-2',
    costPerMChars: 30.0,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-01-01',
  },
  // PlayHT — 2.0
  {
    modelId: 'playht-2',
    provider: 'playht',
    displayName: 'PlayHT 2.0',
    costPerMChars: 30.0,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2023-06-01',
  },
  // FAL — Kokoro
  {
    modelId: 'fal-kokoro',
    provider: 'fal',
    displayName: 'FAL Kokoro',
    costPerMChars: 20.0,
    voiceType: 'standard',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-01-01',
  },
  // FAL — Dia TTS
  {
    modelId: 'fal-dia-tts',
    provider: 'fal',
    displayName: 'FAL Dia TTS',
    costPerMChars: 40.0,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-03-01',
  },
  // FAL — Chatterboxhd
  {
    modelId: 'fal-chatterboxhd',
    provider: 'fal',
    displayName: 'FAL Chatterboxhd',
    costPerMChars: 40.0,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-06-01',
  },
  // FAL — F5 TTS
  {
    modelId: 'fal-f5-tts',
    provider: 'fal',
    displayName: 'FAL F5 TTS',
    costPerMChars: 50.0,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-10-01',
  },
  // FAL — Orpheus TTS
  {
    modelId: 'fal-orpheus-tts',
    provider: 'fal',
    displayName: 'FAL Orpheus TTS',
    costPerMChars: 50.0,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-03-01',
  },
  // Cartesia — Sonic 3
  {
    modelId: 'cartesia-sonic-3',
    provider: 'cartesia',
    displayName: 'Cartesia Sonic 3',
    costPerMChars: 39.0,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-02-01',
  },
  // ElevenLabs — Flash
  {
    modelId: 'elevenlabs-flash',
    provider: 'elevenlabs',
    displayName: 'ElevenLabs Flash',
    costPerMChars: 80.0,
    voiceType: 'standard',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-06-01',
  },
  // ElevenLabs — Multilingual v2
  {
    modelId: 'elevenlabs-multilingual-v2',
    provider: 'elevenlabs',
    displayName: 'ElevenLabs Multilingual v2',
    costPerMChars: 120.0,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-01-01',
  },
  // ElevenLabs — v3
  {
    modelId: 'elevenlabs-v3',
    provider: 'elevenlabs',
    displayName: 'ElevenLabs v3',
    costPerMChars: 120.0,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-04-01',
  },
  // --- Models matching DB modelIds (for backfill) ---
  // Amazon Polly Generative — GA May 2024
  {
    modelId: 'amazon-polly-generative',
    provider: 'amazon',
    displayName: 'Amazon Polly Generative',
    costPerMChars: 100.0,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-05-01',
  },
  {
    modelId: 'amazon-polly-govcloud-neural',
    provider: 'amazon',
    displayName: 'Amazon Polly Neural (GovCloud)',
    costPerMChars: 16.0,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2019-07-30',
  },
  {
    modelId: 'amazon-polly-govcloud-standard',
    provider: 'amazon',
    displayName: 'Amazon Polly Standard (GovCloud)',
    costPerMChars: 4.0,
    voiceType: 'standard',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2016-11-30',
  },
  {
    modelId: 'amazon-polly-long-form',
    provider: 'amazon',
    displayName: 'Amazon Polly Long-Form',
    costPerMChars: 100.0,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2023-01-01',
  },
  {
    modelId: 'azure-custom-deprecated',
    provider: 'azure',
    displayName: 'Azure TTS Custom (Deprecated)',
    costPerMChars: 16.0,
    voiceType: 'standard',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'deprecated',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2018-11-01',
  },
  {
    modelId: 'azure-custom-neural-professional',
    provider: 'azure',
    displayName: 'Azure Custom Neural Voice Professional',
    costPerMChars: 24.0,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2021-10-01',
  },
  {
    modelId: 'azure-custom-neural-professional-hd',
    provider: 'azure',
    displayName: 'Azure Custom Neural Voice Professional HD',
    costPerMChars: 48.0,
    voiceType: 'hd',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-02-01',
  },
  {
    modelId: 'azure-neural-standard',
    provider: 'azure',
    displayName: 'Azure Neural TTS (Standard)',
    costPerMChars: 16.0,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2019-09-01',
  },
  {
    modelId: 'azure-standard-deprecated',
    provider: 'azure',
    displayName: 'Azure TTS Standard (Deprecated)',
    costPerMChars: 4.0,
    voiceType: 'standard',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'deprecated',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2018-11-01',
  },
  {
    modelId: 'cartesia-sonic-turbo',
    provider: 'cartesia',
    displayName: 'Cartesia Sonic-Turbo',
    costPerMChars: 39.0,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-06-01',
  },
  {
    modelId: 'deepgram-aura-1-growth',
    provider: 'deepgram',
    displayName: 'Deepgram Aura-1 (Growth)',
    costPerMChars: 15.0,
    voiceType: 'standard',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-03-12',
  },
  {
    modelId: 'deepgram-aura-1-payg',
    provider: 'deepgram',
    displayName: 'Deepgram Aura-1 (Pay As You Go)',
    costPerMChars: 15.0,
    voiceType: 'standard',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-03-12',
  },
  {
    modelId: 'deepgram-aura-2-growth',
    provider: 'deepgram',
    displayName: 'Deepgram Aura-2 (Growth)',
    costPerMChars: 30.0,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-04-15',
  },
  {
    modelId: 'deepgram-aura-2-payg',
    provider: 'deepgram',
    displayName: 'Deepgram Aura-2 (Pay As You Go)',
    costPerMChars: 30.0,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-04-15',
  },
  {
    modelId: 'google-cloud-chirp3-hd',
    provider: 'google-cloud',
    displayName: 'Google Cloud Chirp 3 HD Voices',
    costPerMChars: 160.0,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-03-17',
  },
  {
    modelId: 'google-cloud-instant-custom-voice',
    provider: 'google-cloud',
    displayName: 'Google Cloud Instant Custom Voice',
    costPerMChars: 160.0,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-03-17',
  },
  {
    modelId: 'google-cloud-neural2',
    provider: 'google-cloud',
    displayName: 'Google Cloud Neural2 Voices',
    costPerMChars: 16.0,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2022-06-01',
  },
  {
    modelId: 'google-cloud-polyglot',
    provider: 'google-cloud',
    displayName: 'Google Cloud Polyglot Voices',
    costPerMChars: 16.0,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2023-06-01',
  },
  {
    modelId: 'google-cloud-polyglot-preview',
    provider: 'google-cloud',
    displayName: 'Google Cloud Polyglot Voices (Preview)',
    costPerMChars: 16.0,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'preview',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2023-06-01',
  },
  {
    modelId: 'google-cloud-standard',
    provider: 'google-cloud',
    displayName: 'Google Cloud Standard Voices',
    costPerMChars: 4.0,
    voiceType: 'standard',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2018-03-27',
  },
  {
    modelId: 'google-cloud-studio',
    provider: 'google-cloud',
    displayName: 'Google Cloud Studio Voices',
    costPerMChars: 160.0,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2023-06-01',
  },
  {
    modelId: 'google-cloud-wavenet',
    provider: 'google-cloud',
    displayName: 'Google Cloud WaveNet Voices',
    costPerMChars: 16.0,
    voiceType: 'wavenet',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2018-03-27',
  },
  {
    modelId: 'openai-tts-hd',
    provider: 'openai',
    displayName: 'OpenAI TTS HD',
    costPerMChars: 30.0,
    voiceType: 'hd',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2023-11-06',
  },
  {
    modelId: 'openai-tts-standard',
    provider: 'openai',
    displayName: 'OpenAI TTS',
    costPerMChars: 15.0,
    voiceType: 'standard',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2023-11-06',
  },
];
