// DO NOT EDIT — generated from registry/*.yaml by `npm run generate-static`
import type { TtsModelPricing } from './types';

export const STATIC_TTS_PRICING: TtsModelPricing[] = [
  {
    modelId: 'amazon-polly-generative',
    provider: 'amazon',
    displayName: 'Amazon Polly Generative',
    costPerMChars: 30,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-05-08',
  },
  {
    modelId: 'amazon-polly-govcloud-neural',
    provider: 'amazon',
    displayName: 'Amazon Polly GovCloud Neural',
    costPerMChars: 19.2,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2020-11-23',
  },
  {
    modelId: 'amazon-polly-govcloud-standard',
    provider: 'amazon',
    displayName: 'Amazon Polly GovCloud Standard',
    costPerMChars: 4.8,
    voiceType: 'standard',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2018-02-28',
  },
  {
    modelId: 'amazon-polly-long-form',
    provider: 'amazon',
    displayName: 'Amazon Polly Long-Form',
    costPerMChars: 100,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2023-11-16',
  },
  {
    modelId: 'amazon-polly-neural',
    provider: 'amazon',
    displayName: 'Amazon Polly Neural',
    costPerMChars: 16,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2019-07-30',
  },
  {
    modelId: 'amazon-polly-standard',
    provider: 'amazon',
    displayName: 'Amazon Polly Standard',
    costPerMChars: 4,
    voiceType: 'standard',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2016-11-30',
  },
  {
    modelId: 'azure-custom-deprecated',
    provider: 'azure',
    displayName: 'Azure Custom TTS (Deprecated)',
    costPerMChars: 6,
    voiceType: 'standard',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'deprecated',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2018-11-01',
  },
  {
    modelId: 'azure-custom-neural-professional',
    provider: 'azure',
    displayName: 'Azure Custom Neural Voice Professional',
    costPerMChars: 24,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2021-02-03',
  },
  {
    modelId: 'azure-custom-neural-professional-hd',
    provider: 'azure',
    displayName: 'Azure Custom Neural Voice Professional HD',
    costPerMChars: 48,
    voiceType: 'hd',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-03-30',
  },
  {
    modelId: 'azure-neural-standard',
    provider: 'azure',
    displayName: 'Azure Neural TTS (Standard)',
    costPerMChars: 15,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2019-05-04',
  },
  {
    modelId: 'azure-standard-deprecated',
    provider: 'azure',
    displayName: 'Azure TTS Standard (Deprecated)',
    costPerMChars: 4,
    voiceType: 'standard',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'deprecated',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2018-11-01',
  },
  {
    modelId: 'azure-tts-custom-deprecated',
    provider: 'azure',
    displayName: 'Azure TTS Custom (Deprecated)',
    costPerMChars: 6,
    voiceType: 'standard',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'deprecated',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: null,
  },
  {
    modelId: 'azure-tts-custom-legacy',
    provider: 'azure',
    displayName: 'Azure TTS Custom (Deprecated)',
    costPerMChars: 6,
    voiceType: 'standard',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'deprecated',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: null,
  },
  {
    modelId: 'azure-tts-custom-professional',
    provider: 'azure',
    displayName: 'Azure Custom Neural Voice Professional',
    costPerMChars: 24,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: null,
  },
  {
    modelId: 'azure-tts-custom-professional-hd',
    provider: 'azure',
    displayName: 'Azure Custom Neural Voice Professional HD',
    costPerMChars: 48,
    voiceType: 'hd',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: null,
  },
  {
    modelId: 'azure-tts-hd-v2',
    provider: 'azure',
    displayName: 'Azure TTS HD V2',
    costPerMChars: 30,
    voiceType: null,
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-06-01',
  },
  {
    modelId: 'azure-tts-neural',
    provider: 'azure',
    displayName: 'Azure Neural TTS',
    costPerMChars: 15,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2019-09-01',
  },
  {
    modelId: 'azure-tts-standard-deprecated',
    provider: 'azure',
    displayName: 'Azure TTS Standard (Deprecated)',
    costPerMChars: 4,
    voiceType: 'standard',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'deprecated',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: null,
  },
  {
    modelId: 'azure-tts-standard-legacy',
    provider: 'azure',
    displayName: 'Azure TTS Standard (Deprecated)',
    costPerMChars: 4,
    voiceType: 'standard',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'deprecated',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: null,
  },
  {
    modelId: 'cartesia-sonic-3',
    provider: 'cartesia',
    displayName: 'Cartesia Sonic-3',
    costPerMChars: 29.875,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-02-01',
  },
  {
    modelId: 'cartesia-sonic-turbo',
    provider: 'cartesia',
    displayName: 'Cartesia Sonic-Turbo',
    costPerMChars: 29.875,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-03-11',
  },
  {
    modelId: 'deepgram-aura-1',
    provider: 'deepgram',
    displayName: 'Deepgram Aura-1',
    costPerMChars: 15,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-01-01',
  },
  {
    modelId: 'deepgram-aura-1-growth',
    provider: 'deepgram',
    displayName: 'Deepgram Aura-1 (Growth)',
    costPerMChars: 13.5,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-03-12',
  },
  {
    modelId: 'deepgram-aura-1-payg',
    provider: 'deepgram',
    displayName: 'Deepgram Aura-1 (Pay As You Go)',
    costPerMChars: 15,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-03-12',
  },
  {
    modelId: 'deepgram-aura-2',
    provider: 'deepgram',
    displayName: 'Deepgram Aura-2',
    costPerMChars: 30,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-01-01',
  },
  {
    modelId: 'deepgram-aura-2-growth',
    provider: 'deepgram',
    displayName: 'Deepgram Aura-2 (Growth)',
    costPerMChars: 27,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-04-15',
  },
  {
    modelId: 'deepgram-aura-2-payg',
    provider: 'deepgram',
    displayName: 'Deepgram Aura-2 (Pay As You Go)',
    costPerMChars: 30,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-04-15',
  },
  {
    modelId: 'elevenlabs-flash',
    provider: 'elevenlabs',
    displayName: 'ElevenLabs Flash',
    costPerMChars: 80,
    voiceType: null,
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-06-01',
  },
  {
    modelId: 'elevenlabs-multilingual-v2',
    provider: 'elevenlabs',
    displayName: 'ElevenLabs Multilingual v2',
    costPerMChars: 120,
    voiceType: null,
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-01-01',
  },
  {
    modelId: 'elevenlabs-standard',
    provider: 'elevenlabs',
    displayName: 'ElevenLabs Standard',
    costPerMChars: 30,
    voiceType: null,
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2023-01-01',
  },
  {
    modelId: 'elevenlabs-v3',
    provider: 'elevenlabs',
    displayName: 'ElevenLabs v3',
    costPerMChars: 120,
    voiceType: null,
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-04-01',
  },
  {
    modelId: 'fal-chatterboxhd',
    provider: 'fal',
    displayName: 'FAL Chatterbox TTS',
    costPerMChars: 25,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-06-01',
  },
  {
    modelId: 'fal-dia-tts',
    provider: 'fal',
    displayName: 'FAL Dia TTS',
    costPerMChars: 40,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-03-01',
  },
  {
    modelId: 'fal-f5-tts',
    provider: 'fal',
    displayName: 'FAL F5 TTS',
    costPerMChars: 50,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2024-10-01',
  },
  {
    modelId: 'fal-kokoro',
    provider: 'fal',
    displayName: 'fal Kokoro TTS (American English)',
    costPerMChars: 20,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-01-01',
  },
  {
    modelId: 'fal-orpheus-tts',
    provider: 'fal',
    displayName: 'FAL Orpheus TTS',
    costPerMChars: 50,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-03-01',
  },
  {
    modelId: 'google-cloud-chirp3-hd',
    provider: 'google-cloud',
    displayName: 'Google Cloud Chirp 3 HD',
    costPerMChars: 30,
    voiceType: 'hd',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-04-02',
  },
  {
    modelId: 'google-cloud-chirp3-instant-custom',
    provider: 'google-cloud',
    displayName: 'Google Cloud Chirp 3 Instant Custom Voice',
    costPerMChars: 60,
    voiceType: 'hd',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: null,
  },
  {
    modelId: 'google-cloud-gemini-2-5-flash-lite-tts',
    provider: 'google-cloud',
    displayName: 'Google Cloud Gemini 2.5 Flash-Lite Preview TTS',
    costPerMChars: 0.5,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'preview',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2026-03-13',
  },
  {
    modelId: 'google-cloud-instant-custom-voice',
    provider: 'google-cloud',
    displayName: 'Google Cloud Instant Custom Voice',
    costPerMChars: 60,
    voiceType: 'hd',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-04-09',
  },
  {
    modelId: 'google-cloud-neural2',
    provider: 'google-cloud',
    displayName: 'Google Cloud Neural2',
    costPerMChars: 16,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2022-06-27',
  },
  {
    modelId: 'google-cloud-polyglot',
    provider: 'google-cloud',
    displayName: 'Google Cloud Polyglot',
    costPerMChars: 16,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'preview',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-04-16',
  },
  {
    modelId: 'google-cloud-polyglot-preview',
    provider: 'google-cloud',
    displayName: 'Google Cloud Polyglot (Preview)',
    costPerMChars: 16,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'preview',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2023-09-01',
  },
  {
    modelId: 'google-cloud-standard',
    provider: 'google-cloud',
    displayName: 'Google Cloud Standard',
    costPerMChars: 4,
    voiceType: 'standard',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2018-03-27',
  },
  {
    modelId: 'google-cloud-studio',
    provider: 'google-cloud',
    displayName: 'Google Cloud Studio',
    costPerMChars: 160,
    voiceType: 'hd',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2023-06-28',
  },
  {
    modelId: 'google-cloud-tts-chirp3',
    provider: 'google-cloud',
    displayName: 'Google Cloud TTS Chirp 3 HD',
    costPerMChars: 30,
    voiceType: 'hd',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: null,
  },
  {
    modelId: 'google-cloud-tts-chirp3-instant-custom',
    provider: 'google-cloud',
    displayName: 'Google Cloud Chirp 3 Instant Custom Voice',
    costPerMChars: 60,
    voiceType: 'hd',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: null,
  },
  {
    modelId: 'google-cloud-tts-neural2',
    provider: 'google-cloud',
    displayName: 'Google Cloud TTS Neural2',
    costPerMChars: 16,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2022-06-01',
  },
  {
    modelId: 'google-cloud-tts-standard',
    provider: 'google-cloud',
    displayName: 'Google Cloud TTS Standard',
    costPerMChars: 4,
    voiceType: 'standard',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2018-03-27',
  },
  {
    modelId: 'google-cloud-tts-studio',
    provider: 'google-cloud',
    displayName: 'Google Cloud TTS Studio',
    costPerMChars: 160,
    voiceType: 'hd',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: null,
  },
  {
    modelId: 'google-cloud-tts-wavenet',
    provider: 'google-cloud',
    displayName: 'Google Cloud TTS WaveNet',
    costPerMChars: 4,
    voiceType: 'wavenet',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2018-03-27',
  },
  {
    modelId: 'google-cloud-wavenet',
    provider: 'google-cloud',
    displayName: 'Google Cloud WaveNet',
    costPerMChars: 4,
    voiceType: 'wavenet',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2018-03-27',
  },
  {
    modelId: 'openai-gpt-4o-mini-tts',
    provider: 'openai',
    displayName: 'OpenAI GPT-4o Mini TTS',
    costPerMChars: 0.6,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: null,
  },
  {
    modelId: 'openai-gpt4o-mini-tts',
    provider: 'openai',
    displayName: 'OpenAI GPT-4o Mini TTS',
    costPerMChars: 0.6,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: null,
  },
  {
    modelId: 'openai-tts-1',
    provider: 'openai',
    displayName: 'OpenAI TTS-1',
    costPerMChars: 15,
    voiceType: 'standard',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2023-11-06',
  },
  {
    modelId: 'openai-tts-1-hd',
    provider: 'openai',
    displayName: 'OpenAI TTS-1 HD',
    costPerMChars: 30,
    voiceType: 'hd',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2023-11-06',
  },
  {
    modelId: 'openai-tts-hd',
    provider: 'openai',
    displayName: 'OpenAI TTS HD',
    costPerMChars: 30,
    voiceType: 'hd',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2023-11-06',
  },
  {
    modelId: 'openai-tts-standard',
    provider: 'openai',
    displayName: 'OpenAI TTS',
    costPerMChars: 15,
    voiceType: 'standard',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2023-11-06',
  },
  {
    modelId: 'playht-2',
    provider: 'playht',
    displayName: 'PlayHT 2.0',
    costPerMChars: 30,
    voiceType: null,
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2023-06-01',
  },
  {
    modelId: 'replicate-inworld-tts-1.5-max',
    provider: 'replicate',
    displayName: 'Inworld TTS 1.5 Max',
    costPerMChars: 10,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: null,
  },
  {
    modelId: 'replicate-inworld-tts-1.5-mini',
    provider: 'replicate',
    displayName: 'Inworld TTS 1.5 Mini',
    costPerMChars: 5,
    voiceType: 'neural',
    maxCharacters: null,
    supportedLanguages: null,
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 99,
    confidenceLevel: 'high',
    freshness: { lastVerified: '', ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: null,
  },
];
