import type { VideoModelPricing } from './types';

export const STATIC_VIDEO_PRICING: VideoModelPricing[] = [
  // Runway — Gen-4 launched 2025-03-31, Gen-4.5 launched 2025-12-01
  // Pricing: $0.01/credit, gen4.5=12 credits/sec, gen4_turbo=5 credits/sec
  {
    modelId: 'runway-gen4-720p',
    provider: 'runway',
    displayName: 'Runway Gen-4 720p',
    costPerMinute: 7.2,
    resolution: '720p',
    maxDuration: 10,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-03-31',
  },
  {
    modelId: 'runway-gen4-turbo-720p',
    provider: 'runway',
    displayName: 'Runway Gen-4 Turbo 720p',
    costPerMinute: 3.0,
    resolution: '720p',
    maxDuration: 10,
    qualityMode: 'turbo',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-03-31',
  },

  // Sora 2 (OpenAI) — launched 2025-09-30
  // API: sora-2=$0.10/sec (720p), sora-2-pro=$0.30/sec (720p) or $0.50/sec (1080p)
  // Max durations: 4, 8, or 12 seconds via API
  {
    modelId: 'sora2-720p',
    provider: 'sora',
    displayName: 'Sora 2 720p',
    costPerMinute: 6.0,
    resolution: '720p',
    maxDuration: 12,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-09-30',
  },
  {
    modelId: 'sora2-pro-720p',
    provider: 'sora',
    displayName: 'Sora 2 Pro 720p',
    costPerMinute: 18.0,
    resolution: '720p',
    maxDuration: 25,
    qualityMode: 'professional',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-09-30',
  },
  {
    modelId: 'sora2-pro-1080p',
    provider: 'sora',
    displayName: 'Sora 2 Pro 1080p',
    costPerMinute: 30.0,
    resolution: '1080p',
    maxDuration: 25,
    qualityMode: 'professional',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-09-30',
  },

  // Google Veo 3.1 — preview 2025-10-15, 4K update 2026-01-13
  // Standard: $0.40/sec (1080p) = $24/min, $0.60/sec (4K) = $36/min
  {
    modelId: 'veo-3.1-1080p',
    provider: 'veo',
    displayName: 'Veo 3.1 1080p',
    costPerMinute: 24.0,
    resolution: '1080p',
    maxDuration: 8,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-10-15',
  },
  {
    modelId: 'veo-3.1-4k',
    provider: 'veo',
    displayName: 'Veo 3.1 4K',
    costPerMinute: 36.0,
    resolution: '4k',
    maxDuration: 8,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-10-15',
  },

  // Kling 3.0 — launched 2026-02-05
  // Official API: $0.084/sec standard (audio off) = $5.04/min, up to 15s
  {
    modelId: 'kling-3.0-1080p',
    provider: 'kling',
    displayName: 'Kling 3.0 1080p',
    costPerMinute: 5.04,
    resolution: '1080p',
    maxDuration: 15,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2026-02-05',
  },

  // Luma Ray 3.14 — launched 2026-01-26
  // Native 1080p, up to 18s, "3x cheaper" than Ray 3
  {
    modelId: 'luma-ray-3.14-1080p',
    provider: 'luma',
    displayName: 'Luma Ray 3.14 1080p',
    costPerMinute: 3.0,
    resolution: '1080p',
    maxDuration: 18,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'low',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2026-01-26',
  },

  // Pika 2.5 — launched ~late Nov 2025 (Pika 2.2 was 2025-02-27)
  // Credit-based, no public API pricing; fal.ai offers Pika v2.2 at $0.06/sec (1080p)
  {
    modelId: 'pika-2.5-1080p',
    provider: 'pika',
    displayName: 'Pika 2.5 1080p',
    costPerMinute: 3.6,
    resolution: '1080p',
    maxDuration: 10,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'low',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-11-24',
  },

  // MiniMax Hailuo 02 — launched 2025-06-18
  // Three configs: 768p-6s, 768p-10s, 1080p-6s
  {
    modelId: 'minimax-hailuo02-768p',
    provider: 'minimax',
    displayName: 'Hailuo 02 768p',
    costPerMinute: 2.7,
    resolution: '768p',
    maxDuration: 10,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-06-18',
  },
  {
    modelId: 'minimax-hailuo02-pro-1080p',
    provider: 'minimax',
    displayName: 'Hailuo 02 Pro 1080p',
    costPerMinute: 4.8,
    resolution: '1080p',
    maxDuration: 6,
    qualityMode: 'professional',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-06-18',
  },

  // Seedance 2.0 (ByteDance) — launched 2026-02-10
  // API via Volcengine/BytePlus, ~$0.08/sec for 1080p = $4.80/min
  {
    modelId: 'seedance-2.0-1080p',
    provider: 'seedance',
    displayName: 'Seedance 2.0 1080p',
    costPerMinute: 4.8,
    resolution: '1080p',
    maxDuration: 15,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'low',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2026-02-10',
  },

  // LTX (Lightricks) — LTX-2.3 launched 2026-03-05
  // Per-second pricing: fast=$0.04/sec (1080p), pro=$0.06/sec (1080p)
  // 4K: fast=$0.16/sec, pro=$0.24/sec
  // Max durations: Fast 1080p=20s, Pro 1080p=10s, Fast 4K=10s, Pro 4K=10s
  {
    modelId: 'ltx-2.3-fast-1080p',
    provider: 'ltx',
    displayName: 'LTX-2.3 Fast 1080p',
    costPerMinute: 2.4,
    resolution: '1080p',
    maxDuration: 20,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2026-03-05',
  },
  {
    modelId: 'ltx-2.3-pro-1080p',
    provider: 'ltx',
    displayName: 'LTX-2.3 Pro 1080p',
    costPerMinute: 3.6,
    resolution: '1080p',
    maxDuration: 10,
    qualityMode: 'professional',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2026-03-05',
  },
  {
    modelId: 'ltx-2.3-fast-4k',
    provider: 'ltx',
    displayName: 'LTX-2.3 Fast 4K',
    costPerMinute: 9.6,
    resolution: '4k',
    maxDuration: 10,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2026-03-05',
  },
  {
    modelId: 'ltx-2.3-pro-4k',
    provider: 'ltx',
    displayName: 'LTX-2.3 Pro 4K',
    costPerMinute: 14.4,
    resolution: '4k',
    maxDuration: 10,
    qualityMode: 'professional',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2026-03-05',
  },

  // MiniMax Hailuo 02 512p — launched 2025-06-18
  {
    modelId: 'minimax-hailuo02-512p',
    provider: 'minimax',
    displayName: 'MiniMax Hailuo 02 512p',
    costPerMinute: 2.7,
    resolution: '512p',
    maxDuration: 6,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-06-18',
  },

  // MiniMax Hailuo 2.3 Fast — launched 2025-10-28
  {
    modelId: 'minimax-hailuo23-fast-1080p',
    provider: 'minimax',
    displayName: 'MiniMax Hailuo 2.3 Fast 1080p',
    costPerMinute: 1.35,
    resolution: '1080p',
    maxDuration: 6,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-10-28',
  },
  {
    modelId: 'minimax-hailuo23-fast-768p',
    provider: 'minimax',
    displayName: 'MiniMax Hailuo 2.3 Fast 768p',
    costPerMinute: 1.35,
    resolution: '768p',
    maxDuration: 6,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-10-28',
  },

  // Seedance 1.5 Pro — launched 2025-12-16
  {
    modelId: 'seedance-1.5-pro-480p',
    provider: 'seedance',
    displayName: 'Seedance 1.5 Pro 480p',
    costPerMinute: 2.4,
    resolution: '480p',
    maxDuration: 10,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-12-16',
  },
  {
    modelId: 'seedance-1.5-pro-480p-audio',
    provider: 'seedance',
    displayName: 'Seedance 1.5 Pro 480p (with audio)',
    costPerMinute: 3.6,
    resolution: '480p',
    maxDuration: 10,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-12-16',
  },
  {
    modelId: 'seedance-1.5-pro-720p',
    provider: 'seedance',
    displayName: 'Seedance 1.5 Pro 720p',
    costPerMinute: 4.8,
    resolution: '720p',
    maxDuration: 10,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-12-16',
  },
  {
    modelId: 'seedance-1.5-pro-720p-audio',
    provider: 'seedance',
    displayName: 'Seedance 1.5 Pro 720p (with audio)',
    costPerMinute: 7.2,
    resolution: '720p',
    maxDuration: 10,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-12-16',
  },

  // FAL — Kling 2.5 Turbo via fal.ai — launched 2025-09-23
  {
    modelId: 'fal-kling2.5-turbo-1080p',
    provider: 'fal',
    displayName: 'FAL Kling 2.5 Turbo Pro 1080p',
    costPerMinute: 5.04,
    resolution: '1080p',
    maxDuration: 10,
    qualityMode: 'turbo',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-09-23',
  },

  // FAL (aggregator) — prices reflect FAL's rates with aggregator markup
  // Veo 3: $0.50/sec (audio off) = $30/min on FAL
  {
    modelId: 'fal-veo3-1080p',
    provider: 'fal',
    displayName: 'FAL Veo 3 1080p',
    costPerMinute: 30.0,
    resolution: '1080p',
    maxDuration: 8,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-10-15',
  },
  // Veo 3 Fast: $0.10/sec (audio off) = $6/min on FAL
  {
    modelId: 'fal-veo3-fast-1080p',
    provider: 'fal',
    displayName: 'FAL Veo 3 Fast 1080p',
    costPerMinute: 6.0,
    resolution: '1080p',
    maxDuration: 8,
    qualityMode: 'turbo',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-10-15',
  },
  // Kling via FAL: $0.168/sec (audio off) = $10.08/min
  {
    modelId: 'fal-kling3-1080p',
    provider: 'fal',
    displayName: 'FAL Kling 3.0 1080p',
    costPerMinute: 10.08,
    resolution: '1080p',
    maxDuration: 15,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'low',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2026-02-05',
  },
  // WAN 2.5 via FAL: $0.05/sec = $3.00/min
  {
    modelId: 'fal-wan2.5-480p',
    provider: 'fal',
    displayName: 'FAL WAN 2.5 480p',
    costPerMinute: 3.0,
    resolution: '480p',
    maxDuration: 5,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'low',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-06-01',
  },
];
