import type { VideoModelPricing } from './types';

export const STATIC_VIDEO_PRICING: VideoModelPricing[] = [
  // Runway — Gen-4 launched 2025-03-31, Gen-4.5 launched 2025-12-01
  {
    modelId: 'runway-gen4-720p',
    provider: 'runway',
    displayName: 'Runway Gen-4 720p',
    costPerMinute: 7.2,
    inputType: 'text,image',
    resolution: '720p',
    maxDuration: 10,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-03-31',
  },
  {
    modelId: 'runway-gen4-turbo-720p',
    provider: 'runway',
    displayName: 'Runway Gen-4 Turbo 720p',
    costPerMinute: 3.0,
    inputType: 'text,image',
    resolution: '720p',
    maxDuration: 10,
    qualityMode: 'turbo',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-03-31',
  },

  // Sora 2 (OpenAI) — launched 2025-09-30
  {
    modelId: 'sora2-720p',
    provider: 'sora',
    displayName: 'Sora 2 720p',
    costPerMinute: 6.0,
    inputType: 'text,image',
    resolution: '720p',
    maxDuration: 12,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-09-30',
  },
  {
    modelId: 'sora2-pro-720p',
    provider: 'sora',
    displayName: 'Sora 2 Pro 720p',
    costPerMinute: 18.0,
    inputType: 'text,image',
    resolution: '720p',
    maxDuration: 25,
    qualityMode: 'professional',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-09-30',
  },
  {
    modelId: 'sora2-pro-1080p',
    provider: 'sora',
    displayName: 'Sora 2 Pro 1080p',
    costPerMinute: 30.0,
    inputType: 'text,image',
    resolution: '1080p',
    maxDuration: 25,
    qualityMode: 'professional',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-09-30',
  },

  // Google Veo 3.1 — preview 2025-10-15, 4K update 2026-01-13
  {
    modelId: 'veo-3.1-1080p',
    provider: 'veo',
    displayName: 'Veo 3.1 1080p',
    costPerMinute: 24.0,
    inputType: 'text,image',
    resolution: '1080p',
    maxDuration: 8,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-10-15',
  },
  {
    modelId: 'veo-3.1-4k',
    provider: 'veo',
    displayName: 'Veo 3.1 4K',
    costPerMinute: 36.0,
    inputType: 'text,image',
    resolution: '4k',
    maxDuration: 8,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-10-15',
  },

  // Kling 3.0 — launched 2026-02-05
  {
    modelId: 'kling-3.0-1080p',
    provider: 'kling',
    displayName: 'Kling 3.0 1080p',
    costPerMinute: 5.04,
    inputType: 'text,image',
    resolution: '1080p',
    maxDuration: 15,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2026-02-05',
  },

  // Luma Ray 3.14 — launched 2026-01-26
  {
    modelId: 'luma-ray-3.14-1080p',
    provider: 'luma',
    displayName: 'Luma Ray 3.14 1080p',
    costPerMinute: 3.0,
    inputType: 'text,image',
    resolution: '1080p',
    maxDuration: 18,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'low',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2026-01-26',
  },

  // Pika 2.5 — launched ~late Nov 2025
  {
    modelId: 'pika-2.5-1080p',
    provider: 'pika',
    displayName: 'Pika 2.5 1080p',
    costPerMinute: 3.6,
    inputType: 'text,image',
    resolution: '1080p',
    maxDuration: 10,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'low',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-11-24',
  },

  // MiniMax Hailuo 02 — launched 2025-06-18
  // Pay-go: https://platform.minimax.io/docs/guides/pricing-paygo
  // 768P 6s=$0.28 → $2.80/min, 1080P 6s=$0.49 → $4.90/min, 512P 6s=$0.10 → $1.00/min
  {
    modelId: 'minimax-hailuo02-768p',
    provider: 'minimax',
    displayName: 'Hailuo 02 768p',
    costPerMinute: 2.8,
    inputType: 'text,image',
    resolution: '768p',
    maxDuration: 10,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-06-18',
  },
  {
    modelId: 'minimax-hailuo02-pro-1080p',
    provider: 'minimax',
    displayName: 'Hailuo 02 Pro 1080p',
    costPerMinute: 4.9,
    inputType: 'text,image',
    resolution: '1080p',
    maxDuration: 6,
    qualityMode: 'professional',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-06-18',
  },

  // Seedance 2.0 (ByteDance) — launched 2026-02-10
  {
    modelId: 'seedance-2.0-1080p',
    provider: 'seedance',
    displayName: 'Seedance 2.0 1080p',
    costPerMinute: 4.8,
    inputType: 'image',
    resolution: '1080p',
    maxDuration: 15,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'low',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2026-02-10',
  },

  // LTX (Lightricks) — LTX-2.3 launched 2026-03-05
  {
    modelId: 'ltx-2.3-fast-1080p',
    provider: 'ltx',
    displayName: 'LTX-2.3 Fast 1080p',
    costPerMinute: 2.4,
    inputType: 'text,image',
    resolution: '1080p',
    maxDuration: 20,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2026-03-05',
  },
  {
    modelId: 'ltx-2.3-pro-1080p',
    provider: 'ltx',
    displayName: 'LTX-2.3 Pro 1080p',
    costPerMinute: 3.6,
    inputType: 'text,image',
    resolution: '1080p',
    maxDuration: 10,
    qualityMode: 'professional',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2026-03-05',
  },
  {
    modelId: 'ltx-2.3-fast-4k',
    provider: 'ltx',
    displayName: 'LTX-2.3 Fast 4K',
    costPerMinute: 9.6,
    inputType: 'text,image',
    resolution: '4k',
    maxDuration: 10,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2026-03-05',
  },
  {
    modelId: 'ltx-2.3-pro-4k',
    provider: 'ltx',
    displayName: 'LTX-2.3 Pro 4K',
    costPerMinute: 14.4,
    inputType: 'text,image',
    resolution: '4k',
    maxDuration: 10,
    qualityMode: 'professional',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2026-03-05',
  },

  // MiniMax Hailuo 02 512p — Pay-go: 512P 6s=$0.10 → $1.00/min
  {
    modelId: 'minimax-hailuo02-512p',
    provider: 'minimax',
    displayName: 'MiniMax Hailuo 02 512p',
    costPerMinute: 1.0,
    inputType: 'text,image',
    resolution: '512p',
    maxDuration: 10,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-06-18',
  },

  // MiniMax Hailuo 2.3 Fast — launched 2025-10-28
  // Pay-go: 1080P 6s=$0.33 → $3.30/min, 768P 6s=$0.19 → $1.90/min
  {
    modelId: 'minimax-hailuo23-fast-1080p',
    provider: 'minimax',
    displayName: 'MiniMax Hailuo 2.3 Fast 1080p',
    costPerMinute: 3.3,
    inputType: 'text,image',
    resolution: '1080p',
    maxDuration: 6,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-10-28',
  },
  {
    modelId: 'minimax-hailuo23-fast-768p',
    provider: 'minimax',
    displayName: 'MiniMax Hailuo 2.3 Fast 768p',
    costPerMinute: 1.9,
    inputType: 'text,image',
    resolution: '768p',
    maxDuration: 10,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-10-28',
  },

  // Seedance 1.5 Pro — launched 2025-12-16
  {
    modelId: 'seedance-1.5-pro-480p',
    provider: 'seedance',
    displayName: 'Seedance 1.5 Pro 480p',
    costPerMinute: 2.4,
    inputType: 'image',
    resolution: '480p',
    maxDuration: 10,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-12-16',
  },
  {
    modelId: 'seedance-1.5-pro-480p-audio',
    provider: 'seedance',
    displayName: 'Seedance 1.5 Pro 480p (with audio)',
    costPerMinute: 3.6,
    inputType: 'image',
    resolution: '480p',
    maxDuration: 10,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-12-16',
  },
  {
    modelId: 'seedance-1.5-pro-720p',
    provider: 'seedance',
    displayName: 'Seedance 1.5 Pro 720p',
    costPerMinute: 4.8,
    inputType: 'image',
    resolution: '720p',
    maxDuration: 10,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-12-16',
  },
  {
    modelId: 'seedance-1.5-pro-720p-audio',
    provider: 'seedance',
    displayName: 'Seedance 1.5 Pro 720p (with audio)',
    costPerMinute: 7.2,
    inputType: 'image',
    resolution: '720p',
    maxDuration: 10,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-12-16',
  },

  // FAL — Kling 2.5 Turbo via fal.ai: $0.07/sec = $4.20/min
  {
    modelId: 'fal-kling2.5-turbo-1080p',
    provider: 'fal',
    displayName: 'FAL Kling 2.5 Turbo Pro 1080p',
    costPerMinute: 4.2,
    inputType: 'text,image',
    resolution: '1080p',
    maxDuration: 10,
    qualityMode: 'turbo',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-09-23',
  },

  // FAL — Veo 3: $0.40/sec = $24/min
  {
    modelId: 'fal-veo3-1080p',
    provider: 'fal',
    displayName: 'FAL Veo 3 1080p',
    costPerMinute: 24.0,
    inputType: 'text',
    resolution: '1080p',
    maxDuration: 8,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-10-15',
  },
  // FAL — Veo 3 Fast: $0.10/sec = $6/min
  {
    modelId: 'fal-veo3-fast-1080p',
    provider: 'fal',
    displayName: 'FAL Veo 3 Fast 1080p',
    costPerMinute: 6.0,
    inputType: 'text',
    resolution: '1080p',
    maxDuration: 8,
    qualityMode: 'turbo',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-10-15',
  },
  // FAL — Kling 3.0: $0.168/sec = $10.08/min
  {
    modelId: 'fal-kling3-1080p',
    provider: 'fal',
    displayName: 'FAL Kling 3.0 1080p',
    costPerMinute: 10.08,
    inputType: 'text,image',
    resolution: '1080p',
    maxDuration: 15,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2026-02-05',
  },
  // FAL — WAN 2.5: $0.05/sec = $3.00/min
  {
    modelId: 'fal-wan2.5-480p',
    provider: 'fal',
    displayName: 'FAL WAN 2.5 480p',
    costPerMinute: 3.0,
    inputType: 'text,image',
    resolution: '480p',
    maxDuration: 5,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'low',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-06-01',
  },

  // FAL — Sora 2: $0.10/sec = $6.00/min (720p, max 12s)
  {
    modelId: 'fal-sora2-720p',
    provider: 'fal',
    displayName: 'FAL Sora 2 720p',
    costPerMinute: 6.0,
    inputType: 'text,image',
    resolution: '720p',
    maxDuration: 12,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-09-30',
  },
  // FAL — Sora 2 Pro: $0.30/sec (720p) = $18/min, $0.50/sec (1080p) = $30/min
  {
    modelId: 'fal-sora2-pro-720p',
    provider: 'fal',
    displayName: 'FAL Sora 2 Pro 720p',
    costPerMinute: 18.0,
    inputType: 'text,image',
    resolution: '720p',
    maxDuration: 25,
    qualityMode: 'professional',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-09-30',
  },
  {
    modelId: 'fal-sora2-pro-1080p',
    provider: 'fal',
    displayName: 'FAL Sora 2 Pro 1080p',
    costPerMinute: 30.0,
    inputType: 'text,image',
    resolution: '1080p',
    maxDuration: 25,
    qualityMode: 'professional',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2025-09-30',
  },

  // FAL — Kling v3 Pro: $0.224/sec = $13.44/min (image-to-video)
  {
    modelId: 'fal-kling-v3-pro-1080p',
    provider: 'fal',
    displayName: 'FAL Kling v3 Pro 1080p',
    costPerMinute: 13.44,
    inputType: 'image',
    resolution: '1080p',
    maxDuration: 15,
    qualityMode: 'professional',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2026-02-05',
  },

  // FAL — Kling O3: $0.168/sec = $10.08/min (image-to-video, 3-15s)
  {
    modelId: 'fal-kling-o3-1080p',
    provider: 'fal',
    displayName: 'FAL Kling O3 1080p',
    costPerMinute: 10.08,
    inputType: 'image',
    resolution: '1080p',
    maxDuration: 15,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2026-02-05',
  },

  // FAL — LTX-2.3: $0.06/sec (1080p) = $3.60/min
  {
    modelId: 'fal-ltx2.3-1080p',
    provider: 'fal',
    displayName: 'FAL LTX-2.3 1080p',
    costPerMinute: 3.6,
    inputType: 'text,image',
    resolution: '1080p',
    maxDuration: 10,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'high',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2026-03-05',
  },

  // FAL — Cosmos 2.5 (NVIDIA): $0.20/video (~5.8s) ≈ $2.07/min
  {
    modelId: 'fal-cosmos2.5-720p',
    provider: 'fal',
    displayName: 'FAL Cosmos 2.5 720p',
    costPerMinute: 2.07,
    inputType: 'text,image',
    resolution: '720p',
    maxDuration: 6,
    qualityMode: 'standard',
    source: 'seed',
    status: 'active',
    confidence: 'low',
    confidenceScore: 65,
    confidenceLevel: 'medium',
    freshness: { lastVerified: new Date().toISOString(), ageHours: 0, stale: false },
    lastUpdated: null,
    launchDate: '2026-01-15',
  },
];
