"""Static avatar pricing data for offline cost calculation."""

from pricetoken.types import AvatarModelPricing, FreshnessInfo

STATIC_AVATAR_PRICING: list[AvatarModelPricing] = [
    # HeyGen — Standard Avatar
    # 1 credit = 1 min of video, $0.99/credit on API plan
    AvatarModelPricing(
        model_id="heygen-avatar-standard",
        provider="heygen",
        display_name="HeyGen Standard Avatar",
        cost_per_minute=0.99,
        avatar_type="standard",
        resolution="1080p",
        max_duration=600,
        quality_mode="standard",
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2024-01-15",
        lip_sync=True,
    ),
    # HeyGen — Interactive Avatar (Avatar IV)
    # 6 credits/min = $5.94/min
    AvatarModelPricing(
        model_id="heygen-avatar-iv",
        provider="heygen",
        display_name="HeyGen Interactive Avatar IV",
        cost_per_minute=5.94,
        avatar_type="premium",
        resolution="1080p",
        max_duration=180,
        quality_mode="premium",
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2025-03-01",
        lip_sync=True,
    ),
    # HeyGen — Video Translation
    # 3 credits/min = $2.97/min
    AvatarModelPricing(
        model_id="heygen-video-translation",
        provider="heygen",
        display_name="HeyGen Video Translation",
        cost_per_minute=2.97,
        avatar_type="translation",
        resolution="1080p",
        max_duration=1800,
        quality_mode="standard",
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2024-06-01",
        lip_sync=True,
    ),
    # HeyGen Avatar III variants — launched 2024-09-12
    AvatarModelPricing(
        model_id="heygen-digital-twin-iii",
        provider="heygen",
        display_name="HeyGen Digital Twin III",
        cost_per_minute=0.99,
        avatar_type="standard",
        resolution="1080p",
        max_duration=600,
        quality_mode="standard",
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2024-09-12",
        lip_sync=True,
    ),
    AvatarModelPricing(
        model_id="heygen-photo-avatar-iii",
        provider="heygen",
        display_name="HeyGen Photo Avatar III",
        cost_per_minute=0.99,
        avatar_type="standard",
        resolution="1080p",
        max_duration=600,
        quality_mode="standard",
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2024-09-12",
        lip_sync=True,
    ),
    AvatarModelPricing(
        model_id="heygen-public-avatar-iii",
        provider="heygen",
        display_name="HeyGen Public Avatar III",
        cost_per_minute=0.99,
        avatar_type="standard",
        resolution="1080p",
        max_duration=600,
        quality_mode="standard",
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2024-09-12",
        lip_sync=True,
    ),
    # HeyGen Avatar IV variants — launched 2025-05-01
    AvatarModelPricing(
        model_id="heygen-digital-twin-iv",
        provider="heygen",
        display_name="HeyGen Digital Twin IV",
        cost_per_minute=5.94,
        avatar_type="premium",
        resolution="1080p",
        max_duration=180,
        quality_mode="premium",
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2025-05-01",
        lip_sync=True,
    ),
    AvatarModelPricing(
        model_id="heygen-photo-avatar-iv",
        provider="heygen",
        display_name="HeyGen Photo Avatar IV",
        cost_per_minute=5.94,
        avatar_type="premium",
        resolution="1080p",
        max_duration=180,
        quality_mode="premium",
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2025-05-01",
        lip_sync=True,
    ),
    AvatarModelPricing(
        model_id="heygen-public-avatar-iv",
        provider="heygen",
        display_name="HeyGen Public Avatar IV",
        cost_per_minute=5.94,
        avatar_type="premium",
        resolution="1080p",
        max_duration=180,
        quality_mode="premium",
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2025-05-01",
        lip_sync=True,
    ),
    # HeyGen Video Translation variants
    AvatarModelPricing(
        model_id="heygen-translate-precision",
        provider="heygen",
        display_name="HeyGen Video Translation Precision Mode",
        cost_per_minute=2.97,
        avatar_type="translation",
        resolution="1080p",
        max_duration=1800,
        quality_mode="standard",
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2025-11-17",
        lip_sync=True,
    ),
    AvatarModelPricing(
        model_id="heygen-translate-speed",
        provider="heygen",
        display_name="HeyGen Video Translation Speed Mode",
        cost_per_minute=2.97,
        avatar_type="translation",
        resolution="1080p",
        max_duration=1800,
        quality_mode="standard",
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2025-11-17",
        lip_sync=True,
    ),
    AvatarModelPricing(
        model_id="heygen-translate-proofread",
        provider="heygen",
        display_name="HeyGen Video Translation Proofread",
        cost_per_minute=2.97,
        avatar_type="translation",
        resolution="1080p",
        max_duration=1800,
        quality_mode="standard",
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2024-08-01",
        lip_sync=False,
    ),
    AvatarModelPricing(
        model_id="heygen-translation-precision",
        provider="heygen",
        display_name="HeyGen Video Translation — Precision Mode",
        cost_per_minute=2.97,
        avatar_type="translation",
        resolution="1080p",
        max_duration=1800,
        quality_mode="standard",
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2025-11-17",
        lip_sync=True,
    ),
    AvatarModelPricing(
        model_id="heygen-translation-speed",
        provider="heygen",
        display_name="HeyGen Video Translation — Speed Mode",
        cost_per_minute=2.97,
        avatar_type="translation",
        resolution="1080p",
        max_duration=1800,
        quality_mode="standard",
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2025-11-17",
        lip_sync=True,
    ),
    AvatarModelPricing(
        model_id="heygen-translation-proofread",
        provider="heygen",
        display_name="HeyGen Video Translation — Proofread",
        cost_per_minute=2.97,
        avatar_type="translation",
        resolution="1080p",
        max_duration=1800,
        quality_mode="standard",
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2024-08-01",
        lip_sync=False,
    ),
]
