"""Static STT pricing data for offline cost calculation."""

from pricetoken.types import FreshnessInfo, SttModelPricing

STATIC_STT_PRICING: list[SttModelPricing] = [
    SttModelPricing(
        model_id="openai-whisper-1",
        provider="openai",
        display_name="OpenAI Whisper",
        cost_per_minute=0.006,
        stt_type="batch",
        max_duration=None,
        supported_languages=None,
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2023-03-01",
    ),
    SttModelPricing(
        model_id="openai-gpt4o-transcribe",
        provider="openai",
        display_name="OpenAI GPT-4o Transcribe",
        cost_per_minute=0.006,
        stt_type="batch",
        max_duration=None,
        supported_languages=None,
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2025-03-01",
    ),
    SttModelPricing(
        model_id="openai-gpt4o-mini-transcribe",
        provider="openai",
        display_name="OpenAI GPT-4o Mini Transcribe",
        cost_per_minute=0.003,
        stt_type="batch",
        max_duration=None,
        supported_languages=None,
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2025-03-01",
    ),
    SttModelPricing(
        model_id="deepgram-nova-3",
        provider="deepgram",
        display_name="Deepgram Nova-3",
        cost_per_minute=0.0077,
        stt_type="streaming",
        max_duration=None,
        supported_languages=None,
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2025-01-15",
    ),
    SttModelPricing(
        model_id="deepgram-nova-3-multilingual",
        provider="deepgram",
        display_name="Deepgram Nova-3 Multilingual",
        cost_per_minute=0.0092,
        stt_type="streaming",
        max_duration=None,
        supported_languages=None,
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2025-01-15",
    ),
    SttModelPricing(
        model_id="deepgram-nova-2",
        provider="deepgram",
        display_name="Deepgram Nova-2",
        cost_per_minute=0.0058,
        stt_type="streaming",
        max_duration=None,
        supported_languages=None,
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2024-01-10",
    ),
    SttModelPricing(
        model_id="assemblyai-universal-2",
        provider="assemblyai",
        display_name="AssemblyAI Universal-2",
        cost_per_minute=0.0025,
        stt_type="batch",
        max_duration=None,
        supported_languages=None,
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2024-06-01",
    ),
    SttModelPricing(
        model_id="google-cloud-stt-standard",
        provider="google-cloud",
        display_name="Google Cloud STT Standard",
        cost_per_minute=0.024,
        stt_type="batch",
        max_duration=None,
        supported_languages=None,
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2018-04-09",
    ),
    SttModelPricing(
        model_id="google-cloud-stt-enhanced",
        provider="google-cloud",
        display_name="Google Cloud STT Enhanced",
        cost_per_minute=0.036,
        stt_type="batch",
        max_duration=None,
        supported_languages=None,
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2019-02-01",
    ),
    SttModelPricing(
        model_id="azure-stt-standard",
        provider="azure",
        display_name="Azure STT Standard",
        cost_per_minute=0.017,
        stt_type="batch",
        max_duration=None,
        supported_languages=None,
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2019-03-01",
    ),
    SttModelPricing(
        model_id="elevenlabs-scribe-v1",
        provider="elevenlabs",
        display_name="ElevenLabs Scribe v1",
        cost_per_minute=0.0067,
        stt_type="batch",
        max_duration=None,
        supported_languages=None,
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2025-02-01",
    ),
    SttModelPricing(
        model_id="elevenlabs-scribe-v2",
        provider="elevenlabs",
        display_name="ElevenLabs Scribe v2",
        cost_per_minute=0.0067,
        stt_type="batch",
        max_duration=None,
        supported_languages=None,
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2025-06-01",
    ),
    SttModelPricing(
        model_id="elevenlabs-scribe-v2-realtime",
        provider="elevenlabs",
        display_name="ElevenLabs Scribe v2 Realtime",
        cost_per_minute=0.008,
        stt_type="streaming",
        max_duration=None,
        supported_languages=None,
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2025-09-01",
    ),
    SttModelPricing(
        model_id="cartesia-ink",
        provider="cartesia",
        display_name="Cartesia Ink",
        cost_per_minute=0.017,
        stt_type="streaming",
        max_duration=None,
        supported_languages=None,
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2025-03-01",
    ),
]
