"""Static TTS pricing data for offline cost calculation."""

from pricetoken.types import FreshnessInfo, TtsModelPricing

STATIC_TTS_PRICING: list[TtsModelPricing] = [
    TtsModelPricing(
        model_id="openai-tts-1",
        provider="openai",
        display_name="OpenAI TTS Standard",
        cost_per_m_chars=15.00,
        voice_type="standard",
        max_characters=None,
        supported_languages=None,
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2023-11-06",
    ),
    TtsModelPricing(
        model_id="openai-tts-1-hd",
        provider="openai",
        display_name="OpenAI TTS HD",
        cost_per_m_chars=30.00,
        voice_type="hd",
        max_characters=None,
        supported_languages=None,
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2023-11-06",
    ),
    TtsModelPricing(
        model_id="google-cloud-tts-standard",
        provider="google-cloud",
        display_name="Google Cloud TTS Standard",
        cost_per_m_chars=4.00,
        voice_type="standard",
        max_characters=None,
        supported_languages=None,
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2018-03-27",
    ),
    TtsModelPricing(
        model_id="google-cloud-tts-wavenet",
        provider="google-cloud",
        display_name="Google Cloud TTS WaveNet",
        cost_per_m_chars=16.00,
        voice_type="wavenet",
        max_characters=None,
        supported_languages=None,
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2018-08-28",
    ),
    TtsModelPricing(
        model_id="google-cloud-tts-neural2",
        provider="google-cloud",
        display_name="Google Cloud TTS Neural2",
        cost_per_m_chars=16.00,
        voice_type="neural",
        max_characters=None,
        supported_languages=None,
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2022-06-01",
    ),
    TtsModelPricing(
        model_id="amazon-polly-standard",
        provider="amazon",
        display_name="Amazon Polly Standard",
        cost_per_m_chars=4.00,
        voice_type="standard",
        max_characters=None,
        supported_languages=None,
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2016-11-30",
    ),
    TtsModelPricing(
        model_id="amazon-polly-neural",
        provider="amazon",
        display_name="Amazon Polly Neural",
        cost_per_m_chars=16.00,
        voice_type="neural",
        max_characters=None,
        supported_languages=None,
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2019-07-30",
    ),
    TtsModelPricing(
        model_id="azure-tts-neural",
        provider="azure",
        display_name="Azure TTS Neural",
        cost_per_m_chars=16.00,
        voice_type="neural",
        max_characters=None,
        supported_languages=None,
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2019-09-01",
    ),
    TtsModelPricing(
        model_id="azure-tts-hd-v2",
        provider="azure",
        display_name="Azure TTS HD V2",
        cost_per_m_chars=30.00,
        voice_type="hd",
        max_characters=None,
        supported_languages=None,
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2024-01-15",
    ),
    TtsModelPricing(
        model_id="elevenlabs-standard",
        provider="elevenlabs",
        display_name="ElevenLabs Standard",
        cost_per_m_chars=30.00,
        voice_type="neural",
        max_characters=None,
        supported_languages=None,
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2023-01-30",
    ),
    TtsModelPricing(
        model_id="deepgram-aura-1",
        provider="deepgram",
        display_name="Deepgram Aura-1",
        cost_per_m_chars=15.00,
        voice_type="standard",
        max_characters=None,
        supported_languages=None,
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2024-01-10",
    ),
    TtsModelPricing(
        model_id="deepgram-aura-2",
        provider="deepgram",
        display_name="Deepgram Aura-2",
        cost_per_m_chars=30.00,
        voice_type="neural",
        max_characters=None,
        supported_languages=None,
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2024-09-01",
    ),
    TtsModelPricing(
        model_id="playht-2",
        provider="playht",
        display_name="PlayHT 2.0",
        cost_per_m_chars=30.00,
        voice_type="neural",
        max_characters=None,
        supported_languages=None,
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2023-09-01",
    ),
    TtsModelPricing(
        model_id="fal-kokoro",
        provider="fal",
        display_name="FAL Kokoro",
        cost_per_m_chars=20.00,
        voice_type="standard",
        max_characters=None,
        supported_languages=None,
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2025-01-01",
    ),
    TtsModelPricing(
        model_id="fal-dia-tts",
        provider="fal",
        display_name="FAL Dia TTS",
        cost_per_m_chars=40.00,
        voice_type="neural",
        max_characters=None,
        supported_languages=None,
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2025-03-01",
    ),
    TtsModelPricing(
        model_id="fal-chatterboxhd",
        provider="fal",
        display_name="FAL Chatterboxhd",
        cost_per_m_chars=40.00,
        voice_type="neural",
        max_characters=None,
        supported_languages=None,
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2025-06-01",
    ),
    TtsModelPricing(
        model_id="fal-f5-tts",
        provider="fal",
        display_name="FAL F5 TTS",
        cost_per_m_chars=50.00,
        voice_type="neural",
        max_characters=None,
        supported_languages=None,
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2024-10-01",
    ),
    TtsModelPricing(
        model_id="fal-orpheus-tts",
        provider="fal",
        display_name="FAL Orpheus TTS",
        cost_per_m_chars=50.00,
        voice_type="neural",
        max_characters=None,
        supported_languages=None,
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2025-03-01",
    ),
    TtsModelPricing(
        model_id="cartesia-sonic-3",
        provider="cartesia",
        display_name="Cartesia Sonic 3",
        cost_per_m_chars=39.00,
        voice_type="neural",
        max_characters=None,
        supported_languages=None,
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2025-02-01",
    ),
    TtsModelPricing(
        model_id="elevenlabs-flash",
        provider="elevenlabs",
        display_name="ElevenLabs Flash",
        cost_per_m_chars=80.00,
        voice_type="standard",
        max_characters=None,
        supported_languages=None,
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2024-06-01",
    ),
    TtsModelPricing(
        model_id="elevenlabs-multilingual-v2",
        provider="elevenlabs",
        display_name="ElevenLabs Multilingual v2",
        cost_per_m_chars=120.00,
        voice_type="neural",
        max_characters=None,
        supported_languages=None,
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2024-01-01",
    ),
    TtsModelPricing(
        model_id="elevenlabs-v3",
        provider="elevenlabs",
        display_name="ElevenLabs v3",
        cost_per_m_chars=120.00,
        voice_type="neural",
        max_characters=None,
        supported_languages=None,
        source="seed",
        status="active",
        confidence="high",
        confidence_score=65,
        confidence_level="medium",
        freshness=FreshnessInfo(last_verified="", age_hours=0, stale=False),
        last_updated=None,
        launch_date="2025-04-01",
    ),
]
