"""Static video pricing data for offline cost calculation."""

from pricetoken.types import VideoModelPricing

STATIC_VIDEO_PRICING: list[VideoModelPricing] = [
    # Runway
    VideoModelPricing(
        model_id="runway-gen4-720p",
        provider="runway",
        display_name="Runway Gen-4 720p",
        cost_per_minute=7.2,
        resolution="720p",
        max_duration=10,
        quality_mode="standard",
        source="seed",
        status="active",
        confidence="high",
        last_updated=None,
        launch_date="2025-06-01",
    ),
    VideoModelPricing(
        model_id="runway-gen4-turbo-720p",
        provider="runway",
        display_name="Runway Gen-4 Turbo 720p",
        cost_per_minute=3.0,
        resolution="720p",
        max_duration=10,
        quality_mode="turbo",
        source="seed",
        status="active",
        confidence="high",
        last_updated=None,
        launch_date="2025-06-01",
    ),
    # Sora (OpenAI)
    VideoModelPricing(
        model_id="sora2-720p",
        provider="sora",
        display_name="Sora 2 720p",
        cost_per_minute=6.0,
        resolution="720p",
        max_duration=20,
        quality_mode="standard",
        source="seed",
        status="active",
        confidence="high",
        last_updated=None,
        launch_date="2025-02-01",
    ),
    VideoModelPricing(
        model_id="sora2-pro-720p",
        provider="sora",
        display_name="Sora 2 Pro 720p",
        cost_per_minute=18.0,
        resolution="720p",
        max_duration=20,
        quality_mode="professional",
        source="seed",
        status="active",
        confidence="high",
        last_updated=None,
        launch_date="2025-02-01",
    ),
    VideoModelPricing(
        model_id="sora2-pro-1080p",
        provider="sora",
        display_name="Sora 2 Pro 1080p",
        cost_per_minute=30.0,
        resolution="1080p",
        max_duration=20,
        quality_mode="professional",
        source="seed",
        status="active",
        confidence="high",
        last_updated=None,
        launch_date="2025-02-01",
    ),
    # Google Veo
    VideoModelPricing(
        model_id="veo-3.1-1080p",
        provider="veo",
        display_name="Veo 3.1 1080p",
        cost_per_minute=12.0,
        resolution="1080p",
        max_duration=8,
        quality_mode="standard",
        source="seed",
        status="active",
        confidence="high",
        last_updated=None,
        launch_date="2025-12-01",
    ),
    VideoModelPricing(
        model_id="veo-3.1-4k",
        provider="veo",
        display_name="Veo 3.1 4K",
        cost_per_minute=24.0,
        resolution="4k",
        max_duration=8,
        quality_mode="standard",
        source="seed",
        status="active",
        confidence="high",
        last_updated=None,
        launch_date="2025-12-01",
    ),
    # Kling
    VideoModelPricing(
        model_id="kling-3.0-4k",
        provider="kling",
        display_name="Kling 3.0 4K",
        cost_per_minute=1.74,
        resolution="4k",
        max_duration=15,
        quality_mode="standard",
        source="seed",
        status="active",
        confidence="high",
        last_updated=None,
        launch_date="2025-09-01",
    ),
    # Luma
    VideoModelPricing(
        model_id="luma-ray-3.14-720p",
        provider="luma",
        display_name="Luma Ray 3.14 720p",
        cost_per_minute=3.0,
        resolution="720p",
        max_duration=10,
        quality_mode="standard",
        source="seed",
        status="active",
        confidence="low",
        last_updated=None,
        launch_date="2025-10-01",
    ),
    # Pika
    VideoModelPricing(
        model_id="pika-2.5-1080p",
        provider="pika",
        display_name="Pika 2.5 1080p",
        cost_per_minute=4.8,
        resolution="1080p",
        max_duration=5,
        quality_mode="standard",
        source="seed",
        status="active",
        confidence="low",
        last_updated=None,
        launch_date="2025-08-01",
    ),
    # MiniMax (Hailuo)
    VideoModelPricing(
        model_id="minimax-hailuo02-768p",
        provider="minimax",
        display_name="Hailuo 02 768p",
        cost_per_minute=2.7,
        resolution="768p",
        max_duration=10,
        quality_mode="standard",
        source="seed",
        status="active",
        confidence="high",
        last_updated=None,
        launch_date="2025-07-01",
    ),
    VideoModelPricing(
        model_id="minimax-hailuo02-pro-1080p",
        provider="minimax",
        display_name="Hailuo 02 Pro 1080p",
        cost_per_minute=4.8,
        resolution="1080p",
        max_duration=10,
        quality_mode="professional",
        source="seed",
        status="active",
        confidence="high",
        last_updated=None,
        launch_date="2025-07-01",
    ),
    # Seedance (ByteDance)
    VideoModelPricing(
        model_id="seedance-2.0-1080p",
        provider="seedance",
        display_name="Seedance 2.0 1080p",
        cost_per_minute=7.2,
        resolution="1080p",
        max_duration=10,
        quality_mode="standard",
        source="seed",
        status="active",
        confidence="low",
        last_updated=None,
        launch_date="2025-11-01",
    ),
    # FAL (aggregator)
    VideoModelPricing(
        model_id="fal-veo3-1080p",
        provider="fal",
        display_name="FAL Veo 3 1080p",
        cost_per_minute=12.0,
        resolution="1080p",
        max_duration=8,
        quality_mode="standard",
        source="seed",
        status="active",
        confidence="high",
        last_updated=None,
        launch_date="2025-12-01",
    ),
    VideoModelPricing(
        model_id="fal-veo3-fast-1080p",
        provider="fal",
        display_name="FAL Veo 3 Fast 1080p",
        cost_per_minute=6.0,
        resolution="1080p",
        max_duration=8,
        quality_mode="turbo",
        source="seed",
        status="active",
        confidence="high",
        last_updated=None,
        launch_date="2025-12-01",
    ),
    VideoModelPricing(
        model_id="fal-kling3-1080p",
        provider="fal",
        display_name="FAL Kling 3.0 1080p",
        cost_per_minute=6.0,
        resolution="1080p",
        max_duration=15,
        quality_mode="standard",
        source="seed",
        status="active",
        confidence="low",
        last_updated=None,
        launch_date="2025-09-01",
    ),
    VideoModelPricing(
        model_id="fal-wan2.1-480p",
        provider="fal",
        display_name="FAL WAN 2.1 480p",
        cost_per_minute=2.4,
        resolution="480p",
        max_duration=5,
        quality_mode="standard",
        source="seed",
        status="active",
        confidence="low",
        last_updated=None,
        launch_date="2025-06-01",
    ),
]
