/**
 * One-time bootstrap script: reads the 6 TS static files and writes
 * corresponding YAML registry files under registry/*.yaml.
 *
 * Strips auto-generated fields (source, confidence*, freshness, lastUpdated)
 * so the YAML only contains contributor-facing data.
 *
 * Usage: npx tsx scripts/bootstrap-registry.ts
 */

import { writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';
import yaml from 'js-yaml';

import { STATIC_PRICING } from '../packages/sdk/src/static';
import { STATIC_TTS_PRICING } from '../packages/sdk/src/tts-static';
import { STATIC_STT_PRICING } from '../packages/sdk/src/stt-static';
import { STATIC_AVATAR_PRICING } from '../packages/sdk/src/avatar-static';
import { STATIC_IMAGE_PRICING } from '../packages/sdk/src/static-image';
import { STATIC_VIDEO_PRICING } from '../packages/sdk/src/video-static';

const ROOT = join(__dirname, '..');
const REGISTRY_DIR = join(ROOT, 'registry');

type StrippedModel = Record<string, unknown>;

/** Fields that are auto-generated by the generator — strip from YAML */
const AUTO_FIELDS = new Set([
  'source', 'confidence', 'confidenceScore', 'confidenceLevel',
  'freshness', 'lastUpdated',
]);

function stripAutoFields(model: Record<string, unknown>): StrippedModel {
  const stripped: StrippedModel = {};
  for (const [key, value] of Object.entries(model)) {
    if (AUTO_FIELDS.has(key)) continue;
    stripped[key] = value;
  }
  return stripped;
}

function sortByModelId<T extends { modelId: string }>(models: T[]): T[] {
  return [...models].sort((a, b) => a.modelId.localeCompare(b.modelId));
}

function writeYaml(filename: string, models: Record<string, unknown>[]): void {
  const sorted = models.sort((a, b) =>
    (a['modelId'] as string).localeCompare(b['modelId'] as string),
  );
  const content = yaml.dump({ models: sorted }, {
    lineWidth: -1,   // no line wrapping
    quotingType: '"', // use double quotes for strings
    forceQuotes: false,
    noRefs: true,
  });
  const path = join(REGISTRY_DIR, filename);
  writeFileSync(path, content, 'utf-8');
  console.log(`  ${filename}: ${sorted.length} models`);
}

function main() {
  mkdirSync(REGISTRY_DIR, { recursive: true });
  console.log('Bootstrapping registry YAML from static TS files...\n');

  // Text
  writeYaml('text.yaml', sortByModelId(STATIC_PRICING).map((m) =>
    stripAutoFields(m as unknown as Record<string, unknown>),
  ));

  // TTS
  writeYaml('tts.yaml', sortByModelId(STATIC_TTS_PRICING).map((m) =>
    stripAutoFields(m as unknown as Record<string, unknown>),
  ));

  // STT
  writeYaml('stt.yaml', sortByModelId(STATIC_STT_PRICING).map((m) =>
    stripAutoFields(m as unknown as Record<string, unknown>),
  ));

  // Avatar
  writeYaml('avatar.yaml', sortByModelId(STATIC_AVATAR_PRICING).map((m) =>
    stripAutoFields(m as unknown as Record<string, unknown>),
  ));

  // Image
  writeYaml('image.yaml', sortByModelId(STATIC_IMAGE_PRICING).map((m) =>
    stripAutoFields(m as unknown as Record<string, unknown>),
  ));

  // Video
  writeYaml('video.yaml', sortByModelId(STATIC_VIDEO_PRICING).map((m) =>
    stripAutoFields(m as unknown as Record<string, unknown>),
  ));

  console.log(`\nDone. Registry files written to ${REGISTRY_DIR}/`);
}

main();
