/**
 * Fetches current pricing from the live API and updates the YAML model
 * registry, then runs generate-static to produce all 12 static files.
 *
 * Flow: API → registry/*.yaml → generate-static → 12 static files
 *
 * Usage: npx tsx scripts/update-static.ts [--url https://pricetoken.ai] [--force]
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { execSync } from 'child_process';
import { join } from 'path';
import yaml from 'js-yaml';

const API_URL = process.env.PRICETOKEN_API_URL ?? 'https://pricetoken.ai';
const FORCE = process.argv.includes('--force');
const ROOT = join(__dirname, '..');
const REGISTRY_DIR = join(ROOT, 'registry');

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

async function fetchData<T>(endpoint: string): Promise<T[]> {
  const res = await fetch(`${API_URL}/api/v1/${endpoint}`);
  if (!res.ok) throw new Error(`${endpoint}: API returned ${res.status}`);
  const json = (await res.json()) as { data: T[] };
  return json.data;
}

/** Fields that are auto-generated by the generator — strip from YAML */
const AUTO_FIELDS = new Set([
  'source', 'confidence', 'confidenceScore', 'confidenceLevel',
  'freshness', 'lastUpdated',
]);

function stripAutoFields(model: Record<string, unknown>): Record<string, unknown> {
  const stripped: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(model)) {
    if (AUTO_FIELDS.has(key)) continue;
    stripped[key] = value;
  }
  return stripped;
}

interface YamlRegistry {
  models: Record<string, unknown>[];
}

function loadExistingYaml(yamlFile: string): Record<string, unknown>[] {
  const path = join(REGISTRY_DIR, yamlFile);
  if (!existsSync(path)) return [];
  try {
    const content = readFileSync(path, 'utf-8');
    const parsed = yaml.load(content) as YamlRegistry;
    return parsed?.models ?? [];
  } catch {
    return [];
  }
}

function writeYaml(filename: string, models: Record<string, unknown>[]): void {
  const sorted = [...models].sort((a, b) =>
    (a['modelId'] as string).localeCompare(b['modelId'] as string),
  );
  const content = yaml.dump({ models: sorted }, {
    lineWidth: -1,
    quotingType: '"',
    forceQuotes: false,
    noRefs: true,
  });
  writeFileSync(join(REGISTRY_DIR, filename), content, 'utf-8');
}

// ---------------------------------------------------------------------------
// Regression detection
// ---------------------------------------------------------------------------

/** Fields to watch for null regressions per modality */
const WATCH_FIELDS: Record<string, string[]> = {
  video: ['inputType'],
};

interface RegressionWarning {
  modelId: string;
  field: string;
  was: unknown;
  now: unknown;
}

function detectRegressions(
  modality: string,
  oldModels: Record<string, unknown>[],
  newModels: Record<string, unknown>[],
): { nulled: RegressionWarning[]; dropped: string[] } {
  const watchFields = WATCH_FIELDS[modality] ?? [];
  const oldByModel = new Map(oldModels.map((m) => [m['modelId'] as string, m]));
  const newByModel = new Map(newModels.map((m) => [m['modelId'] as string, m]));

  const nulled: RegressionWarning[] = [];
  for (const [modelId, newModel] of newByModel) {
    const oldModel = oldByModel.get(modelId);
    if (!oldModel) continue;
    for (const field of watchFields) {
      if (oldModel[field] != null && newModel[field] == null) {
        nulled.push({ modelId, field, was: oldModel[field], now: null });
      }
    }
  }

  const dropped: string[] = [];
  for (const [modelId] of oldByModel) {
    if (!newByModel.has(modelId)) dropped.push(modelId);
  }

  return { nulled, dropped };
}

function printRegressions(modality: string, nulled: RegressionWarning[], dropped: string[]): void {
  if (nulled.length === 0 && dropped.length === 0) return;

  const total = nulled.length + dropped.length;
  console.warn(`\n  ⚠ ${modality}: ${total} potential regression(s):`);
  for (const w of nulled) {
    console.warn(`    ${w.modelId}: ${w.field} was ${JSON.stringify(w.was)}, now null`);
  }
  for (const id of dropped) {
    console.warn(`    ${id}: model REMOVED from API output`);
  }
  if (!FORCE) {
    console.warn(`    → Skipping ${modality}. Run with --force to overwrite anyway.\n`);
  }
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  console.log(`Fetching pricing from ${API_URL} → registry/*.yaml...`);
  if (FORCE) console.log('  --force: will overwrite despite regressions');
  console.log('');

  const modalities = [
    { name: 'text', endpoint: 'text', yamlFile: 'text.yaml' },
    { name: 'tts', endpoint: 'tts', yamlFile: 'tts.yaml' },
    { name: 'stt', endpoint: 'stt', yamlFile: 'stt.yaml' },
    { name: 'avatar', endpoint: 'avatar', yamlFile: 'avatar.yaml' },
    { name: 'image', endpoint: 'image', yamlFile: 'image.yaml' },
    { name: 'video', endpoint: 'video', yamlFile: 'video.yaml' },
  ];

  let hasRegressions = false;
  let updatedCount = 0;

  for (const mod of modalities) {
    try {
      const data = await fetchData<Record<string, unknown>>(mod.endpoint);
      const stripped = data.map(stripAutoFields);
      console.log(`${mod.name}: ${stripped.length} models`);

      // Compare against existing YAML for regressions
      const existingModels = loadExistingYaml(mod.yamlFile);
      const { nulled, dropped } = detectRegressions(mod.name, existingModels, stripped);

      if (nulled.length > 0 || dropped.length > 0) {
        printRegressions(mod.name, nulled, dropped);
        hasRegressions = true;
        if (!FORCE) continue;
      }

      writeYaml(mod.yamlFile, stripped);
      console.log(`  → registry/${mod.yamlFile}`);
      updatedCount++;
    } catch (err) {
      console.error(`${mod.name}: ${err instanceof Error ? err.message : err}`);
    }
  }

  if (hasRegressions && !FORCE) {
    console.warn('\nSome modalities were skipped due to regressions.');
    console.warn('Fix the data in the DB (via seed scripts) and re-run, or use --force.');
    process.exit(1);
  }

  if (updatedCount === 0) {
    console.log('\nNo modalities updated.');
    return;
  }

  // Generate static files from the updated YAML
  console.log('\nGenerating static files from registry YAML...');
  execSync('npx tsx scripts/generate-static.ts', {
    cwd: ROOT,
    stdio: 'inherit',
  });

  console.log('\nDone. Run `npm run ci` to verify.');
}

main().catch((err) => {
  console.error('Failed to update static data:', err);
  process.exit(1);
});
